### ISSUE TITLE
crash: cat data.json | sbot add --

### ISSUE THREAD

**Issue by ralphtheninja** [ssbc/scuttlebot#120]
```
$ cat data.json | sbot add --

/home/lms/src/ssbc/scuttlebot/bin.js:202
          if(err) throw err
                        ^
TypeError: Cannot read property 'type' of null
    at Object.add (/home/lms/src/ssbc/scuttlebot/node_modules/secure-scuttlebutt/feed.js:50:19)
    at Object.add (/home/lms/src/ssbc/scuttlebot/node_modules/cont/node_modules/continuable/to.js:11:28)
    at EventEmitter.api.add (/home/lms/src/ssbc/scuttlebot/lib/api.js:48:10)
    at Object.PacketStream.request (/home/lms/src/ssbc/scuttlebot/node_modules/muxrpc/index.js:79:27)
    at onRequest (/home/lms/src/ssbc/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:26:12)
    at Object.p.write (/home/lms/src/ssbc/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:181:33)
    at /home/lms/src/ssbc/scuttlebot/node_modules/muxrpc/pull-weird.js:52:15
    at loop (/home/lms/src/ssbc/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33)
    at /home/lms/src/ssbc/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/throughs.js:97:9
    at /home/lms/src/ssbc/scuttlebot/node_modules/pull-stream/throughs.js:97:9
```

```
$ cat data.json
{
  "type": "sys-stat",
  "text": {
    "os": {
      "type": "Linux",
      "arch": "x64",
      "platform": "linux",
      "loadavg": [0.41845703125,0.587890625,0.6923828125]
    },
    "process": {
      "memory": 40370176,
      "memoryInfo": {
        "rss": 40370176,
        "vsize": 4081443667968
      },
      "cpu": 0,
      "cpuInfo": {
        "pcpu": 0,
        "pcpuUser": 0,
        "pcpuSystem": 0,
        "cpuTime": 0
      }
    }
  }
}
```

**Comment by ralphtheninja** [comment]
I traced some stuff and for some reason `sbot` doesn't read the `--`. I'll try to dig some more.

/cc @pfraze @dominictarr

**Comment by dominictarr** [comment]
confirmed

**Comment by dominictarr** [comment]
oh okay I told you to do the wrong thing.
 the problem is that optimist has a special meaning for `--`. instead use `sbot add . < data.json` and that will work.

**Comment by ralphtheninja** [comment]
Sweet. Thanks!
