### ISSUE TITLE
Error: method:emit is not on whitelist

### ISSUE THREAD

**Issue by noffle** [ssbc/scuttlebot#141]
Just sync'd to `master` ~20 minutes ago. `sbot server` ran mostly fine, but died shortly after I restarted it with the following:

```
/home/stephen/npm/lib/node_modules/scuttlebot/node_modules/muxrpc/index.js:244
      else     throw err
                     ^
Error: method:emit is not on whitelist
    at Function.perms.pre (/home/stephen/npm/lib/node_modules/scuttlebot/node_modules/muxrpc/permissions.js:74:14)
    at EventEmitter.emitter.emit (/home/stephen/npm/lib/node_modules/scuttlebot/node_modules/muxrpc/index.js:242:23)
    at /home/stephen/npm/lib/node_modules/scuttlebot/plugins/blobs.js:117:13
    at each (/home/stephen/npm/lib/node_modules/scuttlebot/plugins/blobs.js:23:5)
    at got (/home/stephen/npm/lib/node_modules/scuttlebot/plugins/blobs.js:116:7)
    at /home/stephen/npm/lib/node_modules/scuttlebot/plugins/blobs.js:248:16
    at /home/stephen/npm/lib/node_modules/scuttlebot/node_modules/multiblob/index.js:138:23
    at Object.oncomplete (fs.js:108:15)
```

Let me know if I can provide any other details!

**Comment by noffle** [comment]
Actually, now this crash occurs every time I start `sbot server`.

**Comment by dominictarr** [comment]
oops, I made a breaking change to muxrpc by accident. can you reinstall, make sure you get muxrpc@3.3.4 and try again?

**Comment by noffle** [comment]
That seems to have done the trick. My node's been up for the last 30m without issue.
