### ISSUE TITLE
TypeError: Cannot read property 'blobs' of undefined

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/scuttlebot#167]
happened on a new pub server i setup:

```
/usr/lib/node_modules/scuttlebot/plugins/blobs.js:248
        remotes[id].blobs.get(f.id),
                   ^
TypeError: Cannot read property 'blobs' of undefined
    at /usr/lib/node_modules/scuttlebot/plugins/blobs.js:248:20
    at job (/usr/lib/node_modules/scuttlebot/plugins/blobs.js:59:5)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/scuttlebot/plugins/blobs.js:160:16)
    at EventEmitter.emit (events.js:117:20)
    at /usr/lib/node_modules/scuttlebot/index.js:120:16
    at Array.requests.(anonymous function) (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:161:9)
    at onRequest (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:20:27)
    at Object.p.write (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:181:33)
    at /usr/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:52:15
    at loop (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33)
```

**Comment by ahdinosaur** [comment]
repeat of https://github.com/ssbc/phoenix/issues/300?
