### ISSUE TITLE
sbot error publishing content

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/scuttlebot#169]
```
$ cat dino-avatar.json 
{
  "type": "contact",
  "contact": {
    "feed": "uHn+0odK8mnTViRwVnutQkwDqwaioiMkU2eDFbNrzcI=.blake2s"
  },
  "profilePic": {
    "ext": "EkiJgVfqZewHMOSdW9qA0/k+aBLHn1hbkTE+7P5V1J0=.blake2s",
    "size": 166889,
    "type": "image/png",
    "width": 275,
    "height": 275
  }
}
$ cat dino-avatar.json | ssb_host=pub.dinosaur.is sbot publish --                                                                                    

/home/michael/.nvm/versions/io.js/v1.6.2/lib/node_modules/scuttlebot/bin.js:207
          if(err) throw err
                        ^
TypeError: Cannot read property 'type' of null
    at Object.add (/usr/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/node_modules/ssb-feed/index.js:49:19)
    at Object.add (/usr/lib/node_modules/scuttlebot/node_modules/cont/node_modules/continuable/to.js:12:28)
    at EventEmitter.api.publish (/usr/lib/node_modules/scuttlebot/lib/api.js:47:10)
    at Object.PacketStream.request (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/index.js:83:27)
    at onRequest (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:26:12)
    at Object.p.write (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:181:33)
    at /usr/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:52:15
    at loop (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33)
    at /usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/throughs.js:97:9
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-serializer/node_modules/pull-stream/throughs.js:97:9
```

**Comment by pfraze** [comment]
Minimist doesn't include the double-dash in its outputs. We should only use the dot, [the double-dash convention](https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean-also-known-as-bare-double-dash) doesn't fit this.

**Comment by pfraze** [comment]
This command does work if you use `.`

**Comment by dominictarr** [comment]
@ahdinosaur where did you get the code from? I was looking for documentation to fix but couldn't find and example that used `--`

**Comment by ahdinosaur** [comment]
@pfraze enlightened me to that command in IRC.

**Comment by dominictarr** [comment]
closing
