### ISSUE TITLE
wiki: pubServer refuses connection

### ISSUE THREAD

**Issue by cryptix** [ssbc/scuttlebot#188]
I used @dominictarr's invite from the [pubServers](https://github.com/ssbc/scuttlebot/wiki/Pub-Servers) wiki page and got `Sorry, an unexpected error occurred. Please try again.` in the UI. 

The console running sbot printed this after clicking `Use Invite`

```
LOCAL_API { add: 'async',
  publish: 'async',
  get: 'async',
  getPublicKey: 'async',
  getLatest: 'async',
  whoami: 'async',
  auth: 'async',
  relatedMessages: 'async',
  getLocal: 'async',
  query: 'source',
  createFeedStream: 'source',
  createHistoryStream: 'source',
  createLogStream: 'source',
  messagesByType: 'source',
  messagesLinkedToMessage: 'source',
  messagesLinkedToFeed: 'source',
  messagesLinkedFromFeed: 'source',
  feedsLinkedToFeed: 'source',
  feedsLinkedFromFeed: 'source',
  followedUsers: 'source',
  gossip: { seeds: 'async', peers: 'sync', connect: 'async' },
  blobs: 
   { get: 'source',
     has: 'async',
     add: 'sink',
     ls: 'source',
     want: 'async',
     wants: 'sync' },
  invite: { create: 'async', use: 'async', addMe: 'async' },
  friends: { all: 'async', hops: 'async' },
  local: { get: 'sync' },
  phoenix: 
   { createEventStream: 'source',
     getIndexCounts: 'async',
     createInboxStream: 'source',
     createAdvertStream: 'source',
     getRandomAdverts: 'async',
     markRead: 'async',
     markUnread: 'async',
     toggleRead: 'async',
     isRead: 'async',
     subscribe: 'async',
     unsubscribe: 'async',
     toggleSubscribed: 'async',
     isSubscribed: 'async',
     getMyProfile: 'async',
     getProfile: 'async',
     getAllProfiles: 'async',
     getNamesById: 'async',
     getNameTrustRanks: 'async',
     getName: 'async',
     getIdsByName: 'async',
     getActionItems: 'async' } }
info VYAw SBOT 5 connect {"host":"176.58.117.63","port":"2000"}
warn VYAw SBOT 5 unauthed
  Error: connect ECONNREFUSED
      at errnoException (net.js:904:11)
      at Object.afterConnect [as oncomplete] (net.js:895:19)
```

I installed scuttlebot with npm and got version 4.2.3 on a debian stable. 

```
$ npm version
{ http_parser: '1.0',
  node: '0.10.29',
  v8: '3.14.5.8',
  ares: '1.10.0',
  uv: '0.10.27',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1k',
  npm: '1.4.21' }
```

I'm also not sure how to use the other pub servers because they don't include keying information and this seems to be more of an maintenance problem as all of them refuse connections on the listed ports anyway.

```
$ nc 176.58.117.63 2000
(UNKNOWN) [176.58.117.63] 2000 (cisco-sccp) : Connection refused

$ curl http://grimwire.com
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

$ curl http://pub.dinosaur.is
curl: (7) Failed to connect to pub.dinosaur.is port 80: Connection refused

$ curl sbot-pub.ontheshouldersofmany.com:8008
curl: (7) Failed to connect to sbot-pub.ontheshouldersofmany.com port 8008: Connection refused
```

**Comment by pfraze** [comment]
grimwire.com and pub.dinosaur.is are up, but the default port in ssb is 8008. The other two do appear to be down, including dominic's, which is why you got that error. You should get a more descriptive message though, so that's a bug

@dominictarr can you get your pub back online? also, @cryptix I can get you an invite to grimwire if you email me

**Comment by cryptix** [comment]
> I can get you an invite to grimwire if you email me

Sure, email sent. :smile:

**Comment by cryptix** [comment]
works great now! I think we can close this.
