### ISSUE TITLE
Dont leak information over the network in error messages

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#193]
@ralphtheninja reported seeing an error in his pub's console log that was referring to a path on his home machine. (Error: ENOENT: no such file or directory, open '/home/lms/.ssb/blobs/blake2s/a4/e6e3f8d2cbb465bd81411a29dc221a790c1308897db643ae057ccc98312faa') We need to make sure not to send stuff like that over the wire.

**Comment by pfraze** [comment]
```
Error: could not write to tmpfile
   at /root/src/scuttlebot/node_modules/multiblob/index.js:126:29
   at done (/root/src/scuttlebot/node_modules/stream-to-pull-stream/index.js:21:11)
   at /root/src/scuttlebot/node_modules/stream-to-pull-stream/index.js:50:16
   at /root/src/scuttlebot/node_modules/pull-stream/throughs.js:126:7
   at /root/src/scuttlebot/node_modules/pull-stream/throughs.js:21:7
   at Object.weird.read (/root/src/scuttlebot/node_modules/muxrpc/pull-weird.js:31:7)
   at onStream (/root/src/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:87:14)
   at Object.p.write (/root/src/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:182:33)
   at /root/src/scuttlebot/node_modules/muxrpc/pull-weird.js:52:15
 Error: ENOENT: no such file or directory, open '/home/lms/.ssb/blobs/blake2s/f0/52e25778dc926f993ba5d39d35b622b42884b1a7f0bc63cb9ff963fd4554a8'
   at Error (native)
```

**Comment by dominictarr** [comment]
we could clean out the current directory pretty easily, just using `stack.split(curdir).join('./')`
