### ISSUE TITLE
Error: method:auth is not on whitelist

### ISSUE THREAD

**Issue by michielbdejong** [ssbc/scuttlebot#23]
Submitting this as an issue as discussed with @dominictarr:

This is what I'm seeing with commit 93ea9e2 (which is currently @dominictarr's master branch):
````bash
root@Michiel:/scuttlebot# ./client.js add --type follows --'$feed' $ssb_master
Error: method:auth is not on whitelist
    at Function.perms.test (/scuttlebot/node_modules/muxrpc/permissions.js:31:16)
    at Object.PacketStream.request (/scuttlebot/node_modules/muxrpc/index.js:69:27)
    at onRequest (/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:26:12)
    at Object.p.write (/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:173:33)
    at /scuttlebot/node_modules/muxrpc/pull-weird.js:45:15
    at loop (/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33)
    at /scuttlebot/node_modules/muxrpc/node_modules/pull-stream/throughs.js:97:9
    at /scuttlebot/node_modules/pull-stream/throughs.js:97:9
    at /scuttlebot/node_modules/pull-stream/throughs.js:21:7
    at pull (/scuttlebot/node_modules/pull-serializer/node_modules/pull-split/node_modules/pull-through/index.js:35:9)
{
  "previous": "RT1WDBOK8Oe9HMGoYQltATV8ZXBsjicqdAD24fMImlU=.blake2s",
  "author": "mGkIdJ6VJL+pz+USBIYX1wOIR5MJjqUEOZzMcoz1fbg=.blake2s",
  "sequence": 3,
  "timestamp": 1417196219024,
  "hash": "blake2s",
  "content": {
    "type": "follows",
    "$feed": "LONGHASH.blake2s",
    "$rel": "follows"
  },
  "signature": "n32Xi8sAO7xL6H+LYu+ye2AmJO5QZutfJo0oo7C9p5h/9QAktFU0ERMb9hZKfAMNXTKEzUWcsNo0iimsIHPoog==.blake2s.k256"
}
````

Let me know if you need more info!

**Comment by pfraze** [comment]
This is pretty old, going to close. Please re-open if the issue still exists.
