### ISSUE TITLE
Crash error in block plugin on `createHistoryStream`

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#235]
Ran:

```
./bin.js createHistoryStream --id @hxGxqPrplLjRG2vtjQL87abX4QKqeLgCwQpS730nNwE=.ed25519
```

Got:

```
/Users/paulfrazee/scuttlebot/plugins/block.js:50
          if(msg.content.type !== 'contact') return true
                        ^
TypeError: Cannot read property 'type' of undefined
    at /Users/paulfrazee/scuttlebot/plugins/block.js:50:25
    at /Users/paulfrazee/scuttlebot/node_modules/pull-stream/throughs.js:146:11
    at drain (/Users/paulfrazee/scuttlebot/node_modules/pull-paramap/index.js:22:11)
    at /Users/paulfrazee/scuttlebot/node_modules/pull-paramap/index.js:47:13
    at /Users/paulfrazee/scuttlebot/node_modules/secure-scuttlebutt/index.js:251:14
    at /Users/paulfrazee/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level-sublevel/shell.js:102:12
    at /Users/paulfrazee/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level-sublevel/nut.js:121:19
```

**Comment by dominictarr** [comment]
right, that would throw on encrypted messages.

**Comment by dominictarr** [comment]
no, sorry this is caused when history messages have `keys: true`,
okay writing a PR to fix this.
