### ISSUE TITLE
"Read.abort is not a function" fatal error, experienced in pub

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#255]
```
/home/pfraze/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-handshake/node_modules/pull-reader/index.js:87
            return read.abort(abort, cb)
                        ^
TypeError: read.abort is not a function
    at /home/pfraze/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-handshake/node_modules/pull-reader/index.js:87:25
    at Function.reader.abort (/home/pfraze/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-box-stream/node_modules/pull-reader/index.js:65:7)
    at /home/pfraze/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-box-stream/index.js:112:29
    at /home/pfraze/scuttlebot/node_modules/pull-stream/throughs.js:123:12
    at cancel (/home/pfraze/scuttlebot/node_modules/pull-abortable/index.js:13:5)
    at Function.reader.abort (/home/pfraze/scuttlebot/node_modules/pull-abortable/index.js:47:5)
    at abort (/home/pfraze/scuttlebot/node_modules/pull-inactivity/index.js:33:15)
    at null.<anonymous> (/home/pfraze/scuttlebot/node_modules/pull-inactivity/index.js:39:7)
    at wrapper (timers.js:270:19)
    at Timer.listOnTimeout (timers.js:89:15)
```

It's not clear what precedes this.

**Comment by pfraze** [comment]
Version info, this is in node 2.5

```
scuttlebot@7.3.3 /home/pfraze/scuttlebot
├── bash-color@0.0.3
├── broadcast-stream@0.0.0
├── cat-names@1.0.2
├── cont@1.0.3
├── deep-equal@0.2.2
├── dog-names@1.0.2
├── explain-error@1.0.1
├── graphmitter@1.5.0
├── ip@0.3.3
├── ip-regex@1.0.3
├── is-valid-domain@0.0.1
├── level-memview@0.0.0
├── level-sublevel@6.3.17
├── level-test@1.6.6
├── map-merge@1.1.0
├── mdmanifest@1.0.7
├── minimist@1.1.3
├── mkdirp@0.5.1
├── multiblob@1.6.0
├── multicb@1.2.0
├── muxrpc@6.1.2
├── muxrpc-validation@2.0.1
├── muxrpcli@1.0.4
├── mynosql-query@1.0.0
├── noderify@1.0.0
├── nomnom@1.8.0
├── non-private-ip@1.1.0
├── observ@0.2.0
├── observ-debounce@1.1.1
├── on-wakeup@1.0.0
├── osenv@0.1.3
├── packet-stream-codec@1.1.0
├── pull-abortable@4.0.0
├── pull-cat@1.1.8
├── pull-inactivity@2.1.1
├── pull-many@1.0.6
├── pull-notify@0.0.0
├── pull-paramap@1.1.3
├── pull-pushable@1.1.4
├── pull-stream@2.26.1
├── pull-stream-to-stream@1.3.0
├── pull-stringify@1.2.2
├── rimraf@2.4.3
├── secret-stack@2.0.6
├── secure-scuttlebutt@14.1.1
├── ssb-config@1.1.0
├── ssb-feed@2.0.0
├── ssb-keys@4.0.3
├── ssb-msg-schemas@3.2.1
├── ssb-msgs@5.0.0
├── ssb-ref@2.2.1
├── stream-to-pull-stream@1.6.6
├── tape@4.0.3
└── zerr@1.0.3
```

**Comment by dominictarr** [comment]
I wonder how often this is occuring?

**Comment by pfraze** [comment]
Twice so far to me

**Comment by dominictarr** [comment]
twice in how long?

**Comment by pfraze** [comment]
Maybe... a week and a half

**Comment by pfraze** [comment]
Happened again

**Comment by pfraze** [comment]
Happened maybe 3 times in the last 3 days. Pretty frequent! :-1:

**Comment by dominictarr** [comment]
for now, the simplest thing to do to keep this from being a problem is to run your pub in a bash loop.

`while true; do sbot server; done`

that will restart it after a crash, since it is necessary to design a distributed system to be robust to crashes, everything still works just fine with restarts.
