### ISSUE TITLE
read.abort is not a function

### ISSUE THREAD

**Issue by NHQ** [ssbc/scuttlebot#257]
This error brought my pub server down.

```
/usr/local/lib/node_modules/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-handshake/node_modules/pull-reader/index.js:87
            return read.abort(abort, cb)
                        ^

TypeError: read.abort is not a function
    at /usr/local/lib/node_modules/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-handshake/node_modules/pull-reader/index.js:87:25
    at Function.reader.abort (/usr/local/lib/node_modules/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-box-stream/node_modules/pull-reader/index.js:65:7)
    at /usr/local/lib/node_modules/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-box-stream/index.js:114:29
    at /usr/local/lib/node_modules/scuttlebot/node_modules/pull-stream/throughs.js:123:12
    at cancel (/usr/local/lib/node_modules/scuttlebot/node_modules/pull-abortable/index.js:13:5)
    at Function.reader.abort (/usr/local/lib/node_modules/scuttlebot/node_modules/pull-abortable/index.js:47:5)
    at abort (/usr/local/lib/node_modules/scuttlebot/node_modules/pull-inactivity/index.js:33:15)
    at null.<anonymous> (/usr/local/lib/node_modules/scuttlebot/node_modules/pull-inactivity/index.js:39:7)
    at wrapper (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by pfraze** [comment]
Thanks @NHQ, we've got this guy reported already in https://github.com/ssbc/scuttlebot/issues/255, so I'm going to close this as a duplicate.
