### ISSUE TITLE
cb is not a function

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/scuttlebot#264]
[trying to setup a pub server on dokku](https://github.com/ahdinosaur/pub.dinosaur.is), got this error after running `sbot invite.create 1`:

```
/app/node_modules/scuttlebot/plugins/invite.js:73
           else cb(null, addr + '~' + seed.toString('base64'))
                ^

 TypeError: cb is not a function
     at /app/node_modules/scuttlebot/plugins/invite.js:73:16
     at /app/node_modules/secure-scuttlebutt/node_modules/level-sublevel/shell.js:53:51
     at /app/node_modules/secure-scuttlebutt/node_modules/level-sublevel/nut.js:108:13
```

**Comment by pfraze** [comment]
Hm, I'm having trouble reproducing this. @ahdinosaur do you still have it?

**Comment by ahdinosaur** [comment]
eh, i'll re-open if when i try again it's still there.
