### ISSUE TITLE
`Error: opts.port *must* be provided` when using env vars

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/scuttlebot#265]
works fine using default port or setting port via `--port`, but somehow breaks when using environment variables. am i doing something wrong here?

```
$ ssb_port=8008 ./node_modules/scuttlebot/bin.js  
/home/dinosaur/repos/ssbc/patchwork/node_modules/secret-handshake/net.js:31
    throw new Error('opts.port *must* be provided')
    ^

Error: opts.port *must* be provided
    at assertAddr (/home/dinosaur/repos/ssbc/patchwork/node_modules/secret-handshake/net.js:31:11)
    at Object.connect (/home/dinosaur/repos/ssbc/patchwork/node_modules/secret-handshake/net.js:68:7)
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/secret-stack/index.js:67:12
    at Object.<anonymous> (/home/dinosaur/repos/ssbc/patchwork/node_modules/scuttlebot/bin.js:58:38)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
```

**Comment by pfraze** [comment]
Depending on how you look at it, this is a bug in secret-stack for requiring the port provided to be a Number, or a bug in ssb-config for not converting the port string into a Number. I'm going to assume the former.

**Comment by dominictarr** [comment]
fixed in latest secret-stack
