### ISSUE TITLE
EADDRNOTAVAIL when starting a pub

### ISSUE THREAD

**Issue by bcomnes** [ssbc/scuttlebot#296]
I'm trying to run a pub but I'm getting a `EADDRNOTAVAIL` error.  I don't see any port clashing though.

```sh
sbot server --host pi.bret.io
Log level: notice
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 73.157.213.24:8008
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1223:19)
    at listen (net.js:1272:10)
    at net.js:1381:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
```

```sh
bret-raspi:scuttlebot bret$ sudo netstat -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      220/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      218/sshd            
tcp6       0      0 :::5355                 :::*                    LISTEN      220/systemd-resolve 
tcp6       0      0 :::22                   :::*                    LISTEN      218/sshd            
udp        0      0 0.0.0.0:57492           0.0.0.0:*                           195/avahi-daemon: r 
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           195/avahi-daemon: r 
udp        0      0 0.0.0.0:5355            0.0.0.0:*                           220/systemd-resolve 
udp        0      0 192.168.1.110:68        0.0.0.0:*                           200/systemd-network 
udp6       0      0 :::5353                 :::*                                195/avahi-daemon: r 
udp6       0      0 :::5355                 :::*                                220/systemd-resolve 
udp6       0      0 :::38735                :::*                                195/avahi-daemon: r 
udp6       0      0 fe80::ba27:ebff:fe0:546 :::*                                200/systemd-network 
raw6       0      0 :::58                   :::*                    7           200/systemd-network 
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     15912    1221/sshd: bret@pts  /tmp/ssh-DWwdIDOGJg/agent.1221
unix  2      [ ACC ]     STREAM     LISTENING     9521     1/init               /var/run/avahi-daemon/socket
unix  2      [ ACC ]     STREAM     LISTENING     9524     1/init               /run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     1151     1/init               /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     1175     1/init               /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     1182     1/init               /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     9895     344/systemd          /run/user/1000/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     9899     344/systemd          /run/user/1000/bus
unix  2      [ ACC ]     SEQPACKET  LISTENING     1196     1/init               /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     10470    350/sshd: bret@pts/  /tmp/ssh-NhGFx3G41J/agent.350
```

**Comment by clehner** [comment]
Is 73.157.213.24 an address of a local interface? (what is the output of `ifconfig`?)
secret-stack is listening trying to listen on the config'd host since ssbc/secret-stack#4 and ssbc/secret-stack@09bff1064b815284561075246adf1d4b51608d23. secret-stack or scuttlebot should probably be updated to listen on :: instead of the hostname (unless you specifically want to restrict the addresses to which connections can be made)

**Comment by bcomnes** [comment]
Another hint:  leaving off the `--host pi.bret.io` flag lets the server launch without error.   Any suggestions?

```
ret-raspi:~ bret$ sudo ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.110  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::ba27:ebff:fe02:c55c  prefixlen 64  scopeid 0x20<link>
        inet6 2601:1c0:6100:197f:ba27:ebff:fe02:c55c  prefixlen 64  scopeid 0x0<global>
        ether b8:27:eb:02:c5:5c  txqueuelen 1000  (Ethernet)
        RX packets 13779  bytes 1170820 (1.1 MiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 11431  bytes 2089942 (1.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 16300  bytes 9203752 (8.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16300  bytes 9203752 (8.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by clehner** [comment]
@bcomnes for now you should be able to get around this issue by going into `scuttlebot/node_modules/secret-stack/` and applying this diff:
```diff
diff --git a/index.js b/index.js
index 161379d..3c49d1e 100644
--- a/index.js
+++ b/index.js
@@ -100,7 +100,7 @@ module.exports = function (opts) {
       var peers = api.peers = {}

       var server = snet.createServer(setupRPC)
-      server.listen(port, opts.host)
+      server.listen(port)

       function setupRPC (stream, manf) {
         var rpc = Muxrpc(create.manifest, manf || create.manifest)(api, stream.auth)
```

**Comment by bcomnes** [comment]
@clehner that fixed it for now.

**Comment by pfraze** [comment]
@clehner nice job, let's turn this into a PR

**Comment by bcomnes** [comment]
@pfraze done

**Comment by pfraze** [comment]
@dominictarr this just affected somebody else. Do we want to merge https://github.com/ssbc/secret-stack/pull/6 or is there a better way to handle it?

**Comment by pfraze** [comment]
@dominictarr we need to solve this, let's make a call

**Comment by bcomnes** [comment]
Sorry, I wasn't able to find time to dive deeper on this thus far.  Feel free to do whats best.

**Comment by pfraze** [comment]
@dominictarr bump
