### ISSUE TITLE
Occasional failures in the Travis builds

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#331]
I've noticed two different occasional errors in the Travis test runs, which suggests race conditions.

The first is in the invites:

```
TAP version 13
# test invite api
/home/travis/build/ssbc/scuttlebot/test/invite.js:37
      if(err) throw explain(err, 'cannot create invite code')
                    ^
Error: cannot create invite code
    at /home/travis/build/ssbc/scuttlebot/test/invite.js:37:21
    at Object._requests.(anonymous function) (/home/travis/build/ssbc/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:37:5)
    at PacketStream.destroy (/home/travis/build/ssbc/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:73:66)
  Error: unexpected end of parent stream
    at PacketStream.destroy (/home/travis/build/ssbc/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:68:11)
    at PacketStream.write (/home/travis/build/ssbc/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:121:41)
    at /home/travis/build/ssbc/scuttlebot/node_modules/muxrpc/pull-weird.js:58:44
    at /home/travis/build/ssbc/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/sinks.js:11:20
    at /home/travis/build/ssbc/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/throughs.js:97:9
    at Object.cb (/home/travis/build/ssbc/scuttlebot/node_modules/packet-stream-codec/index.js:98:24)
    at drain (/home/travis/build/ssbc/scuttlebot/node_modules/packet-stream-codec/node_modules/pull-reader/index.js:27:23)
    at /home/travis/build/ssbc/scuttlebot/node_modules/packet-stream-codec/node_modules/pull-reader/index.js:44:18
    at Object.cb (/home/travis/build/ssbc/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-box-stream/index.js:126:18)
    at drain (/home/travis/build/ssbc/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-box-stream/node_modules/pull-reader/index.js:24:14)
```

The other one that I've seen, I dont have handy, but it's in the blobs tests somewhere.

**Comment by pfraze** [comment]
If anybody sees the other failure, paste the dump in here.
