### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/scuttlebot#346]
been open for a while... then suddenly while i'm on the patch of works:

```
RangeError: Maximum call stack size exceeded
    at encodePair (/home/dinosaur/repos/ssbc/patchwork/node_modules/packet-stream-codec/index.js:14:21)
    at Object.<anonymous> (/home/dinosaur/repos/ssbc/patchwork/node_modules/packet-stream-codec/index.js:81:13)
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/pull-through/index.js:56:22
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/pull-goodbye/endable.js:15:26
    at source (/home/dinosaur/repos/ssbc/patchwork/node_modules/secret-stack/node_modules/muxrpc/pull-weird.js:46:30)
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/pull-goodbye/endable.js:6:7
    at pull (/home/dinosaur/repos/ssbc/patchwork/node_modules/pull-through/index.js:49:11)
    at next (/home/dinosaur/repos/ssbc/patchwork/node_modules/looper/index.js:7:11)
    at module.exports (/home/dinosaur/repos/ssbc/patchwork/node_modules/looper/index.js:13:5)
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/pull-through/index.js:39:7
```

**Comment by dominictarr** [comment]
I'm seeing errors like these if we just read too fast, it's not an infinite loop, it's just a very big stack.
I think it's because of this: https://github.com/pull-stream/pull-stream/blob/master/sinks.js#L27-L49
there we use a loop where possible, to avoid using `setImmediate` (which is much slower than a loop)
but I guess we need to sometimes chuck in a setImmediate to make sure the stack doesn't get too big.
