### ISSUE TITLE
When we create invites and users try to add them patchwork crashes 

### ISSUE THREAD

**Issue by fredhampton** [ssbc/scuttlebot#360]
We are testing the latest install of scuttlebot 
We have set up a pub
When we create invites and users try to add them patchwork crashes 
When the users start patchwork again they are following the pub

Is there a log file that we can check to see what errors are showing up ?
Is the current version os scuttlebot compatible with the current version of patchwork ?

Thanks

**Comment by dominictarr** [comment]
Ah, yeah it should be. What sort of crash is it? does it exit? Open the dev tools, with `ctrl-shift-i` and see if it shows anything.

**Comment by fredhampton** [comment]
It Exits …..I will open up dev tools to see if it says anything 


Thanks !!!


On October 6, 2016 at 6:27:28 PM, Dominic Tarr (notifications@github.com) wrote:

Ah, yeah it should be. What sort of crash is it? does it exit? Open the dev tools, with ctrl-shift-i and see if it shows anything.

**Comment by dominictarr** [comment]
I have confirmed this, got this error in the terminal
```
 Connect attempt wx.larpa.net:8008:@DTNmX+4SjsgZ7xyDh5xxmNtFqa6pWi5Qtw7cE8aR9TQ=.ed25519
Error: not a valid address:{"host":"net:wx.larpa.net","port":8008,"key":"DTNmX+4SjsgZ7xyDh5xxmNtFqa6pWi5Qtw7cE8aR9TQ="}
    at Object.<anonymous> (/home/dominic/c/patchwork-electron/app/node_modules/scuttlebot/plugins/gossip/index.js:120:17)
    at apply (/home/dominic/c/patchwork-electron/app/node_modules/muxrpc-validation/index.js:173:15)
    at Object.<anonymous> (/home/dominic/c/patchwork-electron/app/node_modules/muxrpc-validation/index.js:62:14)
    at Object.<anonymous> (/home/dominic/c/patchwork-electron/app/node_modules/secret-stack/util.js:80:17)
    at Object.<anonymous> (/home/dominic/c/patchwork-electron/app/node_modules/hoox/index.js:3:17)
    at Object.hooked [as add] (/home/dominic/c/patchwork-electron/app/node_modules/hoox/index.js:10:15)
    at /home/dominic/c/patchwork-electron/app/node_modules/scuttlebot/plugins/invite.js:220:49
    at Object._requests.(anonymous function) (/home/dominic/c/patchwork-electron/app/node_modules/packet-stream/index.js:37:5)
    at PacketStream._onrequest (/home/dominic/c/patchwork-electron/app/node_modules/packet-stream/index.js:139:26)
    at PacketStream.write (/home/dominic/c/patchwork-electron/app/node_modules/packet-stream/index.js:122:41)

```
should be able to fix that...

**Comment by dominictarr** [comment]
okay, this is fixed by https://github.com/ssbc/patchwork/pull/420
I'm gonna merge that PR

**Comment by fredhampton** [comment]
Thanks !!!!
Do we need to also update our pub ?

**Comment by dominictarr** [comment]
you can if you want, though some people are reporting problems upgrading, so you might want to hold off on that a little.

**Comment by fredhampton** [comment]
What is the stable version ?


On October 8, 2016 at 4:11:03 PM, Dominic Tarr (notifications@github.com) wrote:

you can if you want, though some people are reporting problems upgrading, so you might want to hold off on that a little.
