### ISSUE TITLE
server error Error: wrong number

### ISSUE THREAD

**Issue by myf** [ssbc/scuttlebot#366]
there are a fair large number of such errors (perhaps 5 per minute) when i run a pub, I wonder if it has to do with a high cpu usage as well

```
server error Error: wrong number
    at abort (/home/myf/.npm_packages/lib/node_modules/scuttlebot/node_modules/secret-handshake/handshake.js:69:43)
    at Object.cb (/home/myf/.npm_packages/lib/node_modules/scuttlebot/node_modules/secret-handshake/handshake.js:86:20)
    at drain (/home/myf/.npm_packages/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:39:14)
    at more (/home/myf/.npm_packages/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:51:13)
    at /home/myf/.npm_packages/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:62:9
    at /home/myf/.npm_packages/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:20:7
    at drain (/home/myf/.npm_packages/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/myf/.npm_packages/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:150:5)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

**Comment by dominictarr** [comment]
that means someone tried to connect to your pub, but thought you where a different key. If you have changed the key, but kept the same host then this will happen.

**Comment by evbogue** [comment]
I get this error all of the time even though the key is right.

**Comment by fredhampton** [comment]
Also receive this error on a fresh install

server error Error: wrong number
    at abort (/usr/lib/node_modules/scuttlebot/node_modules/secret-handshake/handshake.js:69:43)
    at Object.cb (/usr/lib/node_modules/scuttlebot/node_modules/secret-handshake/handshake.js:86:20)
    at drain (/usr/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:39:14)
    at more (/usr/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:51:13)
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:62:9
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:20:7
    at drain (/usr/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/usr/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:150:5)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

**Comment by dominictarr** [comment]
Oh, btw, if you generate a new key on the same ip address, then you will see this error.

@fredhampton hey, btw, I sent you a private message on patchwork, can you check it?

**Comment by don-smith** [comment]
I've run into this when running pubs from Docker images. Most of the time the keys are created when you first `docker run ...` the image. If the container shuts down at any time and you `run` again (instead of the more appropriate `docker start`) on the same host/public IP, you'll see this when its contacts attempt their handshakes.

**Comment by evbogue** [comment]
@myf Are you still getting a large number of these errors? If not we can close.
