### ISSUE TITLE
server error Error: expected challenge

### ISSUE THREAD

**Issue by myf** [ssbc/scuttlebot#370]
when connected to certain peers i received the following error

```
server error Error: expected challenge
    at abort (/home/myf/src/scuttlebot/node_modules/secret-handshake/handshake.js:69:43)
    at Object.cb (/home/myf/src/scuttlebot/node_modules/secret-handshake/handshake.js:73:22)
    at drain (/home/myf/src/scuttlebot/node_modules/pull-reader/index.js:42:23)
    at /home/myf/src/scuttlebot/node_modules/pull-reader/index.js:59:18
    at /home/myf/src/scuttlebot/node_modules/pull-reader/index.js:20:7
    at drain (/home/myf/src/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/myf/src/scuttlebot/node_modules/stream-to-pull-stream/index.js:162:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12)
```

**Comment by soyuka** [comment]
Hi! 

I've the same error and I might miss some configuration. 

I'm trying to connect `ssb-client` to the `sbot server` via websockets.

This is the code:

```
ssbClient(keys, {
  remote: 'ws://localhost:8989',
  manifest: require('./manifest.json'),
}, function(err, sbot) {
  if (err) { throw err }
```

I didn't study what the manifest is about yet (just hacking with sbot for now) and I've taken the one from [patchwork](https://raw.githubusercontent.com/ssbc/patchbay/2264a334a0bf3da0cda5d13e61903a94651feafe/manifest.json).

Note that I made sure the ssb-ws plugin was enabled.

Can you help me figure out why it fails to connect? Thanks!

**Comment by dominictarr** [comment]
@soyuka are you connecting from code running in the browser? if so you'll need to make sure that your sbot is following the key in the browser. it should follow `keys.id`

**Comment by carloslfu** [comment]
I am using [easy-ssb-pub](https://github.com/staltz/easy-ssb-pub) and have the same issue, this is my log:

```
server error Error: expected challenge
    at abort (/usr/src/app/node_modules/secret-handshake/handshake.js:69:43)
    at Object.cb (/usr/src/app/node_modules/secret-handshake/handshake.js:73:22)
    at drain (/usr/src/app/node_modules/pull-reader/index.js:42:23)
    at /usr/src/app/node_modules/pull-reader/index.js:59:18
    at /usr/src/app/node_modules/pull-reader/index.js:20:7
    at drain (/usr/src/app/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/usr/src/app/node_modules/stream-to-pull-stream/index.js:162:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:498:12)
Connected h.transitiontech.ca:8008:@+MXnwq3uxVq6ey1tZsdhD6d7ZEauA7eVJy0NgzYZ/io=.ed25519
server error Error: expected challenge
    at abort (/usr/src/app/node_modules/secret-handshake/handshake.js:69:43)
    at Object.cb (/usr/src/app/node_modules/secret-handshake/handshake.js:73:22)
    at drain (/usr/src/app/node_modules/pull-reader/index.js:42:23)
    at /usr/src/app/node_modules/pull-reader/index.js:59:18
    at /usr/src/app/node_modules/pull-reader/index.js:20:7
    at drain (/usr/src/app/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/usr/src/app/node_modules/stream-to-pull-stream/index.js:158:5)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
server error Error: expected challenge
    at abort (/usr/src/app/node_modules/secret-handshake/handshake.js:69:43)
    at Object.cb (/usr/src/app/node_modules/secret-handshake/handshake.js:73:22)
    at drain (/usr/src/app/node_modules/pull-reader/index.js:42:23)
    at /usr/src/app/node_modules/pull-reader/index.js:59:18
    at /usr/src/app/node_modules/pull-reader/index.js:20:7
    at drain (/usr/src/app/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/usr/src/app/node_modules/stream-to-pull-stream/index.js:158:5)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
Connected ssb.interweb.technology:8008:@CQSMJsDjpn5t59MXqMp1q3JJ3+19K9Jn0Z3LQfZkVBI=.ed25519
Connected ssb.interweb.technology:8008:@CQSMJsDjpn5t59MXqMp1q3JJ3+19K9Jn0Z3LQfZkVBI=.ed25519
/usr/src/app/node_modules/multiblob/index.js:184
        else if(opts.max != null && opts.max < stat.size)
                                                   ^

TypeError: Cannot read property 'size' of undefined
    at /usr/src/app/node_modules/multiblob/index.js:184:52
    at done (/usr/src/app/node_modules/multiblob/index.js:41:38)
    at FSReqWrap.oncomplete (fs.js:123:15)

```

**Comment by dominictarr** [comment]
that last error is fixed if you update to latest multiblob (simplest is run `rm -rf node_modules; npm install`)

**Comment by dominictarr** [comment]
the other errors arn't serious, they are just failed connections (which happen sometimes in a p2p network)

**Comment by carloslfu** [comment]
Thanks @dominictarr this fixed the issue for me
