### ISSUE TITLE
No .read for stream

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#38]
On local RPC exchanges, this sometimes occurs:

```
no .read for stream: -2 dropped: { req: 2,
  seq: 2,
  end: 
   { message: 'method:createHistoryStream is not on whitelist',
     name: 'Error',
     stack: 'Error: method:createHistoryStream is not on whitelist\n    at Function.perms.test (/Users/paulfrazee/scuttlebot/node_modules/muxrpc/permissions.js:42:14)\n    at Object.stream.read (/Users/paulfrazee/scuttlebot/node_modules/muxrpc/index.js:82:29)\n    at onStream (/Users/paulfrazee/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:119:18)\n    at Object.p.write (/Users/paulfrazee/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:174:33)\n    at /Users/paulfrazee/scuttlebot/node_modules/muxrpc/pull-weird.js:45:15\n    at loop (/Users/paulfrazee/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33)\n    at /Users/paulfrazee/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/throughs.js:97:9\n    at /Users/paulfrazee/scuttlebot/node_modules/pull-stream/throughs.js:97:9\n    at /Users/paulfrazee/scuttlebot/node_modules/pull-stream/throughs.js:21:7\n    at pull (/Users/paulfrazee/scuttlebot/node_modules/pull-serializer/node_modules/pull-split/node_modules/pull-through/index.js:35:9)' } }
```

After a few of those, it sometimes crashes the server with
```
/Users/paulfrazee/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:70
          stream.read(null, err)
                 ^
TypeError: Property 'read' of object #<Object> is not a function
    at Object.stream.destroy (/Users/paulfrazee/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:70:18)
    at /Users/paulfrazee/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:187:11
    at Array.forEach (native)
    at Object.p.destroy (/Users/paulfrazee/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:185:17)
    at Object.p.write (/Users/paulfrazee/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:171:24)
    at source (/Users/paulfrazee/scuttlebot/node_modules/muxrpc/pull-weird.js:34:15)
    at /Users/paulfrazee/scuttlebot/node_modules/muxrpc/node_modules/pull-goodbye/endable.js:6:7
    at /Users/paulfrazee/scuttlebot/node_modules/pull-stream/throughs.js:13:5
    at /Users/paulfrazee/scuttlebot/node_modules/pull-ws-server/node_modules/pull-ws/sink.js:40:16
    at module.exports (/Users/paulfrazee/scuttlebot/node_modules/pull-ws-server/node_modules/pull-ws/ready.js:21:12)
```

**Comment by pfraze** [comment]
This is getting handled in other issues
