### ISSUE TITLE
Error when pub tries to accept invite

### ISSUE THREAD

**Issue by cblgh** [ssbc/scuttlebot#391]
I'm running a pub at ssb.cblgh.org, and trying to get a pub running with only sbot (as opposed to easy-ssb-pub, which I was running at first, but then I felt I wanted to have my own thing).

Here are the errors I've seen:
New account trying to accept Pub invite code via Patchwork (no progress in Patchwork after the button text reads _Requesting Follow_; not even error message). 
```
Error replicating with @vhrc5ZapTwPTyDYu3rLWB8cQiFtjnf/v2zcQQ3sy7/g=.ed25519:
   Error: no source:createHistoryStream
    at Object.localCall (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/local-api.js:29:13)
    at Object.<anonymous> (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/local-api.js:37:22)
    at PacketStreamSubstream.stream.read (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/stream.js:67:23)
    at PacketStream._onstream (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:228:11)
    at PacketStream.write (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:133:41)
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/pull-weird.js:56:15
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-stream/sinks/drain.js:24:37
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream-codec/index.js:107:11)
```

I've also seen the following when trying to add an invite code to a pub I'm already friends with (just to see if I could, and if the pub was running properly).
```
server error, from net:::ffff:192.168.1.1:49680~shs:
Error: expected hello
    at abort (/usr/lib/node_modules/scuttlebot/node_modules/secret-handshake/protocol.js:80:45)
    at Object.cb (/usr/lib/node_modules/scuttlebot/node_modules/secret-handshake/protocol.js:90:26)
    at drain (/usr/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:42:23)
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:59:18
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:20:7
    at drain (/usr/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/usr/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:158:5)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
server error, from net:::ffff:192.168.1.1:49681~shs:
Error: expected hello
    at abort (/usr/lib/node_modules/scuttlebot/node_modules/secret-handshake/protocol.js:80:45)
    at Object.cb (/usr/lib/node_modules/scuttlebot/node_modules/secret-handshake/protocol.js:90:26)
    at drain (/usr/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:42:23)
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:59:18
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:20:7
    at drain (/usr/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/usr/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:158:5)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
```

```
Error replicating with @2q5LyuiS+X2X4Sef96riCCdyPiTq3cAPWhPIIYZfrYk=.ed25519:
   Error: no source:createHistoryStream
    at Object.localCall (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/local-api.js:29:13)
    at Object.<anonymous> (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/local-api.js:37:22)
    at PacketStreamSubstream.stream.read (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/stream.js:67:23)
    at PacketStream._onstream (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:228:11)
    at PacketStream.write (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:133:41)
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/pull-weird.js:56:15
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-stream/sinks/drain.js:24:37
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream-codec/index.js:107:11)
    at drain (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-reader/index.js:39:14)
```

Strangely enough, my test account seems to have befriended and connected to the pub anyway? Not sure what's going on really.

(When using easy-ssb-pub, I had to set the SWARM_PORT; I'm wondering if my neglecting to set the equivalent using only sbot has to do with my issues? I'm not sure.)

**Comment by dominictarr** [comment]
oh, these arn't fatal errors. but should be fixed to save time and so people don't open issues about them. the createHistoryStream one is because it's trying to replicate with the invite code, which is wrong obviously. (this will be fixed soon)
and the expected hello thing is when it makes a connection but doesn't do the handshake for some reason. a good p2p protocol has to be robust, in general, so if everything otherwise seems okay, this isn't a problem.

**Comment by cblgh** [comment]
Ah thanks for the explanation, sorry for the issues! Just trying to work out what's what :~
