### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/scuttlebot#399]
new pub crash :boom: 

```
/usr/src/app/node_modules/muxrpc/stream.js:41
      args.push(function (err, value) {
          ^

TypeError: Cannot read property 'push' of undefined
    at Object.request (/usr/src/app/node_modules/muxrpc/stream.js:41:11)
    at PacketStream._onrequest (/usr/src/app/node_modules/packet-stream/index.js:159:17)
    at PacketStream.write (/usr/src/app/node_modules/packet-stream/index.js:132:41)
    at /usr/src/app/node_modules/muxrpc/pull-weird.js:56:15
    at /usr/src/app/node_modules/pull-stream/sinks/drain.js:24:37
    at /usr/src/app/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/usr/src/app/node_modules/packet-stream-codec/index.js:107:11)
    at drain (/usr/src/app/node_modules/pull-reader/index.js:39:14)
    at more (/usr/src/app/node_modules/pull-reader/index.js:51:13)
    at /usr/src/app/node_modules/pull-reader/index.js:62:9
```

**Comment by ahdinosaur** [comment]
looking at [`muxrpc`](https://github.com/ssbc/muxrpc), it seems like it'd be caused by receiving a bad request, since i can't see where we're validating the shape of input.
