### ISSUE TITLE
RangeError: Index out of range

### ISSUE THREAD

**Issue by erde74** [ssbc/scuttlebot#413]
i get a lot of RangeError messages
```
buffer.js:840
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:840:11)
    at Buffer.readUInt32BE (buffer.js:914:5)
    at /home/ssb/scuttlebot/node_modules/aligned-block-file/blocks.js:90:29
    at /home/ssb/scuttlebot/node_modules/aligned-block-file/blocks.js:34:36
    at /home/ssb/scuttlebot/node_modules/aligned-block-file/file.js:45:13
    at FSReqWrap.wrapper [as oncomplete] (fs.js:628:17)

```

OS: NetBSD 7.1
Node: v7.7.3

i had to manually build and install leveldown and sodium-native, there is no package for netbsd.

**Comment by erde74** [comment]
as ev suggested, ssb-ebt@1.0.8 seems to fix the problem for me

**Comment by erde74** [comment]
fixed
