### ISSUE TITLE
limbo state, possibly through incomplete transaction

### ISSUE THREAD

**Issue by myf** [ssbc/scuttlebot#416]
I was trying to post something but it didn;t go through. Then I realized that i cannot start `sbot server` anymore, the stack trace is
```
➜  .ssb sbot server
Log level: notice
Listening on http://localhost:7718/
[fulltext] since 1497495078022
/home/myf/.ssb_main/node_modules/ssb-fulltext/index.js:22
          if(err) throw err
                  ^

Error: when trying to retrive:1497503891252.002at since:111080651
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/flumeview-level/index.js:116:26
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/flumelog-offset/inject.js:65:17
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/flumelog-offset/frame/recoverable.js:40:11
    at Object.read (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:44:14)
  Error: past end
    at Object.read (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:44:17)
    at next (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/flumelog-offset/frame/recoverable.js:39:16)
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/flumelog-offset/frame/recoverable.js:35:11
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:91:11
    at get (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:25:7)
    at Object.readUInt32BE (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:88:9)
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/flumelog-offset/frame/recoverable.js:33:16
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:91:11
    at get (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:25:7)
    at Object.readUInt32BE (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:88:9)
```

any ideas on how to solve this?

**Comment by myf** [comment]
after i comment out `ssb-fulltext` from the config i got some more intersting errors
```
➜  ~ sbot server    
Log level: notice
Listening on http://localhost:7718/
.................................................. (indexes:0%)Connected theos.kyriasis.com:12593:@IytsV0aRJv8nodJ5QZv8+IvKVz4guTSmvkUcCU+gQGs=.ed25519
Error: when trying to retrive:link,@0kWtrq7IG4OM4+fzf1gFQI6+xYAUc2WvLUXPWI3eMHE=.ed25519,vote,%codRB+H30Nsaq56Jq2ACnyeZ9RgGMHOSgv65GtvoCIs=.sha256,103,%Fg0Q2eyqVm+k5IpvxQkLmYykyejxQeDK8Vm/y5o+e7c=.sha256at since:111074656
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/flumeview-level/index.js:116:26
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/flumelog-offset/inject.js:65:17
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/flumelog-offset/frame/recoverable.js:24:22
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:89:26
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:34:36
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/file.js:27:18
  Error: aligned-block-file/file.get: requested block index was greater than max, got:6780, expected less than or equal to:6779
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/file.js:27:21
    at Function.many.once (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/obv/index.js:38:49)
    at Object.get (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/file.js:24:14)
    at get (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:30:12)
    at Object.readUInt32BE (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/aligned-block-file/blocks.js:88:9)
    at Object.getMeta (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/flumelog-offset/frame/recoverable.js:23:12)
    at Object.get (/home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/flumelog-offset/inject.js:64:13)
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/flumeview-level/index.js:115:17
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/pull-paramap/index.js:41:11
    at /home/myf/.npm-packages/lib/node_modules/scuttlebot/node_modules/pull-stream/throughs/filter.js:17:11
Disconnected theos.kyriasis.com:12593:@IytsV0aRJv8nodJ5QZv8+IvKVz4guTSmvkUcCU+gQGs=.ed25519

```

it runs but just doesn't do anything

**Comment by evbogue** [comment]
@myf are you getting these errors with patchwork classic?

**Comment by evbogue** [comment]
@myf try deleting your `flume` and `fulltext0` folders in `~/.ssb` ?

**Comment by dominictarr** [comment]
@myf sorry I just saw this now!

yes it looks like your indexes are out of wack.
I can see you are on 10 from the error message, yeah try deleting the fulltext index. `~/.ssb/fulltext0` and the flume indexes `rm ~./ssb/flume/*.json ~/.ssb/flume/*/*`
(avoid deleting `~/.ssb/flume/log.offset`)

**Comment by myf** [comment]
closed, stale
