### ISSUE TITLE
Problem installing level-down-v1.7.2-node-v48-darwin-x64

### ISSUE THREAD

**Issue by yangwao** [ssbc/scuttlebot#426]
```
⫸  sudo npm i -g scuttlebot
/usr/local/bin/scuttlebot -> /usr/local/lib/node_modules/scuttlebot/bin.js
/usr/local/bin/sbot -> /usr/local/lib/node_modules/scuttlebot/bin.js

> leveldown@1.7.2 install /usr/local/lib/node_modules/scuttlebot/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.0
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.7.2-node-v48-darwin-x64.tar.gz
prebuild-install WARN install EACCES: permission denied, access '/Users/wao/.npm'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/scuttlebot/node_modules/leveldown/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/scuttlebot/node_modules/leveldown
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wao/.npm/_logs/2017-07-08T13_46_45_297Z-debug.log
```
I think it's problem with that path directories does not exists.
```
⫸  ls -lah /usr/local/lib/node_modules/scuttlebot
ls: /usr/local/lib/node_modules/scuttlebot: No such file or directory
```
I think there should be `mkdir -p`

**Comment by ralphtheninja** [comment]
This seems to be related to problems in `prebuild-install` where `ensureNpmCacheDir()` fails https://github.com/mafintosh/prebuild-install/blob/master/download.js#L138-L159

**Comment by ralphtheninja** [comment]
@yangwao Do you have any more information on the `EACCES` error?

**Comment by ralphtheninja** [comment]
Or rather, we see errors from both `prebuild-install` (which fails) and then `node-gyp` also fails

**Comment by dominictarr** [comment]
oh it's not the recommended pattern to use root - if you use root doesn't it downgrade perms before it runs scripts (to nobody? or this might be how a really old npm worked) it looks like npm is running as root, but prebuild-install isn't.

**Comment by schollz** [comment]
I'm getting a similar problem on Linux x64: 

```shell
/usr/local/bin/sbot -> /usr/local/lib/node_modules/scuttlebot/bin.js
/usr/local/bin/scuttlebot -> /usr/local/lib/node_modules/scuttlebot/bin.js

> sodium-native@2.0.1 install /usr/local/lib/node_modules/scuttlebot/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"


> leveldown@1.7.2 install /usr/local/lib/node_modules/scuttlebot/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.4.1
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.7.2-node-v57-linux-x64.tar.gz
prebuild-install WARN install EACCES: permission denied, access '/home/zns/.npm'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/scuttlebot/node_modules/leveldown/build'
gyp ERR! System Linux 4.10.0-40-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/scuttlebot/node_modules/leveldown
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/scuttlebot/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zns/.npm/_logs/2017-12-11T12_56_09_866Z-debug.log
```

I was able to install by adding some flags:

```
sudo npm install -g scuttlebot --unsafe-perm=true --allow-root
```

**Comment by interfect** [comment]
I ran into this trying to get `scuttlebot` installed on my mac, so I could get `git-ssb` installed from the `ssb-npm-registry`. Everything ends up depending on `leveldown`, which won't build without `--unsafe-perm=true --allow-root` if you're trying to install the software at the system level.

**Comment by christianbundy** [comment]
@interfect I don't think we should be depending on leveldown@1.7.2 in recent versions of Scuttlebot, could you post the output of `npm ls scuttlebot` and `npm ls leveldown`?

**Comment by interfect** [comment]
It's now leveldown@3.0.2 that is giving me trouble, but as far as I can tell it's the same error.

Here's my install log, and my attempts to use `npm ls`; I don't think `npm ls` is working, because I can't get `scuttlebot` installed:

```
Vyoma:~ anovak$ sudo npm install -g scuttlebot
/opt/local/bin/sbot -> /opt/local/lib/node_modules/scuttlebot/bin.js
/opt/local/bin/scuttlebot -> /opt/local/lib/node_modules/scuttlebot/bin.js

> fsevents@1.2.4 install /opt/local/lib/node_modules/scuttlebot/node_modules/fsevents
> node install

node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.4 and node@9.4.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/opt/local/lib/node_modules/scuttlebot/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64' 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /opt/local/lib/node_modules/scuttlebot/node_modules/fsevents
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/local/bin/node /opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/local/lib/node_modules/scuttlebot/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/scuttlebot/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/local/lib/node_modules/scuttlebot/node_modules/fsevents
node-pre-gyp ERR! node -v v9.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok 
Failed to execute '/opt/local/bin/node /opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)

> sodium-native@2.2.2 install /opt/local/lib/node_modules/scuttlebot/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"


> leveldown@3.0.2 install /opt/local/lib/node_modules/scuttlebot/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/Users/anovak/.npm'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/local/lib/node_modules/scuttlebot/node_modules/leveldown/build'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/local/lib/node_modules/scuttlebot/node_modules/leveldown
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/scuttlebot/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anovak/.npm/_logs/2018-10-21T22_31_40_534Z-debug.log
Vyoma:~ anovak$ npm ls scuttlebot
/Users/anovak
└── (empty)

Vyoma:~ anovak$ npm ls leveldown
/Users/anovak
└── (empty)

Vyoma:~ anovak$ sudo npm ls -g scuttlebot
/opt/local/lib
└── (empty)

Vyoma:~ anovak$ sudo npm ls -g leveldown
/opt/local/lib
└── (empty)

Vyoma:~ anovak$ 
```

**Comment by christianbundy** [comment]
> I was able to install by adding some flags:
>
>```sh
>sudo npm install -g scuttlebot --unsafe-perm=true --allow-root
>```

I think this is the correct answer. See [the NPM documentation](https://docs.npmjs.com/misc/scripts#user) on installing with root, which specifies that you *must* use `--unsafe-perm` to run scripts as root. Here's the command that's working for me (as root):

```sh
npm install --unsafe-perm --global leveldown
```

I appreciate you letting us know about this issue, but since this is the intended usage of NPM I don't think we're in a position to make those changes for you. I'm going to close this as *wontfix*, although "can't fix" is probably more appropriate. Please let me know if you have any questions.
