### ISSUE TITLE
leveldown does not build on Raspberry PI running Ubuntu Mate 16.04

### ISSUE THREAD

**Issue by elleko** [ssbc/scuttlebot#429]
Reproduction Steps:
1. on a Raspberry Pi, run npm install -g scuttlebot 
2. when install is complete, run sbot seever

Result:
returns error below:

@bb-desktop:~$ sbot server
/home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/build/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/build/Debug/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/build/Release/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/out/Debug/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/Debug/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/out/Release/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/Release/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/build/default/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/compiled/7.10.1/linux/arm/leveldown.node
    at bindings (/home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/level/level.js:1:106)
bb@bb-desktop:~$ sbot server
/home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/build/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/build/Debug/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/build/Release/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/out/Debug/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/Debug/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/out/Release/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/Release/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/build/default/leveldown.node
 → /home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/compiled/7.10.1/linux/arm/leveldown.node
    at bindings (/home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebot/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bb/.nvm/versions/node/v7.10.1/lib/node_modules/scuttlebotv/node_modules/level/level.js:1:106)

**Comment by dominictarr** [comment]
what npm version do you have? it might be worth updating to the latest node, it's possible that there is a prebuild available for arm. otherwise, try `npm run rebuild`

**Comment by elleko** [comment]
hi-

l was indeed running an older version npm. updated and installed again, 
woks fine.

-B

**Comment by dominictarr** [comment]
awesome!
