### ISSUE TITLE
sbot server error on start

### ISSUE THREAD

**Issue by MarinaAditazz** [ssbc/scuttlebot#446]
after `npm install -g scuttlebot` today, when i do `sbot server` i get the following error:

```
flumelog-offset: blockSize and codec params moved into an object. https://github.com/flumedb/flumelog-offset
Log level: notice
.................................................. (indexes:-100%)[fulltext] since 0
.................................................. (indexes:-400%)/home/marina/prefix/lib/node_modules/scuttlebot/node_modules/async-single/proto.js:23
  if(value === null) throw new Error('cannot write null')
                     ^
Error: cannot write null
    at Single._write (/home/marina/prefix/lib/node_modules/scuttlebot/node_modules/async-single/proto.js:23:28)
    at Timer.unrefdHandle (timers.js:462:14)
```

any ideas?

**Comment by MarinaAditazz** [comment]
just as an update, i removed all the logs except log.offset and then ran sbot server to reindex. then it worked!
