### ISSUE TITLE
Travis tests/builds always fail

### ISSUE THREAD

**Issue by amsross** [ssbc/scuttlebot#447]
Travis builds are consistently failing. This has been the case for as far back as I went (which was not all that far) in the [build history](https://travis-ci.org/ssbc/scuttlebot/builds).

```
"test-plugin" has been installed. Restart Scuttlebot server to enable the plugin.

ok 1 (unnamed assert)
# installed and enabled plugin is loaded
ok 2 (unnamed assert)
ok 3 (unnamed assert)
ok 4 should be equal
# installed and disabled plugin is not loaded
ok 5 should be equal
# uninstall plugin
uninstalling plugin...

events.js:160
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: lock /tmp/test-plugins1/db/LOCK: already held by process
    at /home/travis/build/ssbc/scuttlebot/node_modules/level-packager/node_modules/levelup/lib/levelup.js:117:34
    at /home/travis/build/ssbc/scuttlebot/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
npm ERR! Test failed.  See above for more details.

The command "npm test" exited with 1.

Done. Your build exited with 1.
```

**Comment by amsross** [comment]
This failure isn't present on `npm test` on OSX 10.11.6 w/ node v6.11.3. This appears to be limited to the travis builds. FWIW, [this build](https://travis-ci.org/ssbc/scuttlebot/builds/285602139#L427) is using node v6.9.5.
