### ISSUE TITLE
bug - `invite.create 1` -> cb is not a function

### ISSUE THREAD

**Issue by kumavis** [ssbc/scuttlebot#457]
```
root@pub:/scuttlebot# ./bin.js invite.create 1 $SSB_CFG

/scuttlebot/node_modules/muxrpcli/index.js:68
      throw err
      ^
TypeError: cb is not a function
    at Object.<anonymous> (/scuttlebot/plugins/invite.js:72:18)
    at apply (/scuttlebot/node_modules/muxrpc-validation/index.js:175:15)
    at Object.<anonymous> (/scuttlebot/node_modules/muxrpc-validation/index.js:82:14)
    at Object.hooked (/scuttlebot/node_modules/hoox/index.js:10:15)
    at Object.localCall (/scuttlebot/node_modules/muxrpc/local-api.js:31:31)
    at Object.<anonymous> (/scuttlebot/node_modules/muxrpc/local-api.js:37:22)
    at Object.request (/scuttlebot/node_modules/muxrpc/stream.js:46:17)
    at PacketStream._onrequest (/scuttlebot/node_modules/packet-stream/index.js:149:17)
    at PacketStream.write (/scuttlebot/node_modules/packet-stream/index.js:122:41)
    at /scuttlebot/node_modules/muxrpc/pull-weird.js:56:15
root@pub:/scuttlebot# echo $SSB_CFG 
--port 8118 --path /shared/pub/.ssb
```

**Comment by dominictarr** [comment]
`sbot server` is the only command that takes config directly, otherwise you need to use a `--` separator.

`./bin.js invite.create 1 -- $SSB_CFG`
