### ISSUE TITLE
plugins/gossip - TypeError: cb is not a function

### ISSUE THREAD

**Issue by kumavis** [ssbc/scuttlebot#458]
versions:
local: fresh npm install
pub: fresh clone from master

- start my hosted pub (modified from https://github.com/don-smith/ssb-tutorial)
( ignore user1 and user2 )
```
$ docker-compose up                                                                                                        
Starting user2 ... 
Starting pub ... 
Starting user1 ... 
Starting user1
Starting user2
Starting user2 ... done
Attaching to pub, user1, user2
user1    | Loading plugins from /shared/user1/.ssb/node_modules
user2    | Loading plugins from /shared/user2/.ssb/node_modules
pub      | Loading plugins from /shared/pub/.ssb/node_modules
user2    | Log level: notice
user1    | Log level: notice
user1    | Connected 172.18.0.3:8118:@l9NV0hAzxkFw1xbz2+qn40XB9jcPY0LI20P3u/ojYyA=.ed25519
pub      | Log level: notice
pub      | Connected 172.18.0.2:8118:@B8QApCq8UuftPCwlHpUCKgb7wad4SsYNkq/+h9qS9Ts=.ed25519
user2    | Connected 172.18.0.2:8118:@B8QApCq8UuftPCwlHpUCKgb7wad4SsYNkq/+h9qS9Ts=.ed25519
```

- start my local sbot
```
$ sbot server --path ~/.ssb2 --port 8118                                                                                          1 ↵
flumelog-offset: blockSize and codec params moved into an object. https://github.com/flumedb/flumelog-offset
Log level: notice
************************************************** (indexes:100%)
```

- instruct local sbot to connect
```
sbot gossip.connect 198.199.103.240:8118:@3CNNeW0Zj64m+pXk71rgP1FKJlBpRDm6IW3C3QtYoMU=.ed25519 --path ~/.ssb2 --port 8118       1 ↵
/Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/muxrpcli/index.js:68
      throw err
      ^

Error: unexpected end of parent stream
    at PacketStream.destroy (/Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:133:41)
    at source (/Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:43:24)
    at /Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/pull-goodbye/endable.js:6:7
    at /Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/pull-through/index.js:31:16
    at /Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/pull-through/index.js:31:16
    at source (/Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/pull-pair/index.js:21:7)
    at /Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/pull-cat/index.js:7:11
    at Array.forEach (<anonymous>)
    at abortAll (/Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/pull-cat/index.js:6:7)
```

- as seen in local sbot logs:
```
CONNECT 198.199.103.240:8118:@3CNNeW0Zj64m+pXk71rgP1FKJlBpRDm6IW3C3QtYoMU=.ed25519
Connected 198.199.103.240:8118:@3CNNeW0Zj64m+pXk71rgP1FKJlBpRDm6IW3C3QtYoMU=.ed25519
/Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/plugins/gossip/index.js:189
          cb && cb(null, rpc)
                ^

TypeError: cb is not a function
    at /Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/plugins/gossip/index.js:189:17
    at /Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/secret-stack/index.js:231:36
    at next (/Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/multiserver/compose.js:28:14)
    at /Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/multiserver/compose.js:34:9
    at _cb (/Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/multiserver/plugins/shs.js:31:11)
    at /Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/secret-handshake/protocol.js:120:7
    at Object.cb (/Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/secret-handshake/protocol.js:55:11)
    at drain (/Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:39:14)
    at more (/Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:51:13)
    at /Users/kumavis/.nvm/versions/node/v8.7.0/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:62:9
```

- as seen in pub logs:
```
pub      | Error: unexpected hangup
pub      |     at Object.cb (/scuttlebot/node_modules/pull-box-stream/index.js:117:44)
pub      |     at drain (/scuttlebot/node_modules/pull-reader/index.js:42:23)
pub      |     at /scuttlebot/node_modules/pull-reader/index.js:59:18
pub      |     at /scuttlebot/node_modules/pull-reader/index.js:110:13
pub      |     at drain (/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
pub      |     at Socket.<anonymous> (/scuttlebot/node_modules/stream-to-pull-stream/index.js:158:5)
pub      |     at emitNone (events.js:91:20)
pub      |     at Socket.emit (events.js:185:7)
pub      |     at endReadableNT (_stream_readable.js:974:12)
pub      |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
pub      | Error: unexpected hangup
pub      |     at Object.cb (/scuttlebot/node_modules/pull-box-stream/index.js:117:44)
pub      |     at drain (/scuttlebot/node_modules/pull-reader/index.js:42:23)
pub      |     at /scuttlebot/node_modules/pull-reader/index.js:59:18
pub      |     at /scuttlebot/node_modules/pull-reader/index.js:110:13
pub      |     at drain (/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
pub      |     at Socket.<anonymous> (/scuttlebot/node_modules/stream-to-pull-stream/index.js:158:5)
pub      |     at emitNone (events.js:91:20)
pub      |     at Socket.emit (events.js:185:7)
pub      |     at endReadableNT (_stream_readable.js:974:12)
pub      |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
pub      | Error: unexpected hangup
pub      |     at Object.cb (/scuttlebot/node_modules/pull-box-stream/index.js:117:44)
pub      |     at drain (/scuttlebot/node_modules/pull-reader/index.js:42:23)
pub      |     at /scuttlebot/node_modules/pull-reader/index.js:59:18
pub      |     at /scuttlebot/node_modules/pull-reader/index.js:110:13
pub      |     at drain (/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
pub      |     at Socket.<anonymous> (/scuttlebot/node_modules/stream-to-pull-stream/index.js:158:5)
pub      |     at emitNone (events.js:91:20)
pub      |     at Socket.emit (events.js:185:7)
pub      |     at endReadableNT (_stream_readable.js:974:12)
pub      |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

**Comment by dominictarr** [comment]
same problem as in https://github.com/ssbc/scuttlebot/issues/457
