### ISSUE TITLE
Failure trying to use createUserStream sbot command

### ISSUE THREAD

**Issue by bdionne** [ssbc/scuttlebot#461]
Getting the following stack trying to use `sbot createUserStream <id>`

````
/Users/bitdiddle/.nvm/versions/node/v6.9.1/lib/node_modules/scuttlebot/node_modules/muxrpcli/index.js:68
      throw err
      ^
Error
    at ZE (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/zerr/index.js:11:42)
    at Object.ZError [as Type] (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/zerr/index.js:13:14)
    at validate (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc-validation/index.js:138:22)
    at Object.<anonymous> (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc-validation/index.js:91:17)
    at Object.hooked (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/hoox/index.js:10:15)
    at Object.localCall (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/local-api.js:31:31)
    at Object.<anonymous> (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/local-api.js:37:22)
    at PacketStreamSubstream.stream.read (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/stream.js:67:23)
    at PacketStream._onstream (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:230:11)
    at PacketStream.write (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:135:41)
````

**Comment by bdionne** [comment]
sweet, thanks! Next time I'll read the manual more closely
