### ISSUE TITLE
sbot server Error replicating 

### ISSUE THREAD

**Issue by luandro** [ssbc/scuttlebot#476]
I've been feeling ignored for the past weeks in Patchwork, and finally I was confirmed that my messages weren't being published.

```
scuttlebot 11.1.1 /Users/luandrovieira/.ssb logging.level:notice
my key ID: 2RNGJafZtMHzd76gyvqH6EJiK7kBnXeak5mBWzoO/iU=.ed25519
RELOAD 2 255068915
0 262152 65536 262152
262152 786448 131072 524296
786448 1835032 262144 1048584
1835032 3932192 524288 2097160
RELOADED 255068915
************************************************** (indexes:100%)Error replicating with @FJDMuATvh0a3qIcIPcstUANVIj362fWkYCG5bnkZ5nA=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/Users/luandrovieira/.nvm/versions/node/v8.9.4/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/Users/luandrovieira/.nvm/versions/node/v8.9.4/lib/node_modules/scuttlebot/node_modules/muxrpc/stream.js:114:17)
    at /Users/luandrovieira/.nvm/versions/node/v8.9.4/lib/node_modules/scuttlebot/node_modules/muxrpc/index.js:45:15
    at remoteCall (/Users/luandrovieira/.nvm/versions/node/v8.9.4/lib/node_modules/scuttlebot/node_modules/muxrpc/api.js:26:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/Users/luandrovieira/.nvm/versions/node/v8.9.4/lib/node_modules/scuttlebot/node_modules/muxrpc/api.js:40:20)
    at replicate (/Users/luandrovieira/.nvm/versions/node/v8.9.4/lib/node_modules/scuttlebot/plugins/replicate/legacy.js:247:13)
    at EventEmitter.fallback (/Users/luandrovieira/.nvm/versions/node/v8.9.4/lib/node_modules/scuttlebot/plugins/replicate/legacy.js:307:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
```

Any way to get around this?

**Comment by luandro** [comment]
I deleted the `.ssb` folder, restarted `sbot`, copied my old `secret` and tried running `sbot` again. End up with the same error. I'm also getting a lot of `Error: challenge not accepted`, not sure it's that's normal or that maybe the source of the issue.

**Comment by luandro** [comment]
I had to delete everything (but the `secret`) and start `sbot` again. I'll close since I'm not sure how to replicate this.
