### ISSUE TITLE
Can't start sbot: unexpected token in links.js

### ISSUE THREAD

**Issue by rev138** [ssbc/scuttlebot#480]
When following [this guide](https://scuttlebot.io/docs/config/create-a-pub.html) I get the following error:

> $ sbot server --host ********
scuttlebot 11.1.1 /home/scuttlebutt/.ssb logging.level:notice
my key ID: ********
/usr/lib/node_modules/scuttlebot/node_modules/flumeview-query/links.js:101
      )
      ^
>
> SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/scuttlebot/node_modules/ssb-links/index.js:2:23)

I am using Debian 9 with nodejs v6.13.1

**Comment by arj03** [comment]
Looks like an old version of node that doesn't like trailing , (https://github.com/flumedb/flumeview-query/blob/master/links.js#L100)

**Comment by dominictarr** [comment]
sorry, this is fixed now. they thought they'd make javascript syntax more permissive instead of never ever changing it which would be better

**Comment by gibberfishinc** [comment]
Thank you!
