### ISSUE TITLE
bytewise error: Unknow value

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/scuttlebot#490]
currently ssb.rootsystems.nz is offline due to a repeating error:

```
/home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/bytewise-core/util.js:26
    throw new TypeError(message)
    ^

TypeError: Unknown value
    at util.assert (/home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/bytewise-core/util.js:26:11)
    at Object.bytewise.encode (/home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/bytewise-core/index.js:69:3)
    at Object.util.encodeList [as encode] (/home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/bytewise-core/util.js:145:23)
    at serialize (/home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/bytewise-core/index.js:23:22)
    at Object.bytewise.encode (/home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/bytewise-core/index.js:60:18)
    at Object.util.encodeList [as encode] (/home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/bytewise-core/util.js:145:23)
    at serialize (/home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/bytewise-core/index.js:23:22)
    at Object.bytewise.encode (/home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/bytewise-core/index.js:60:18)
    at Codec.encodeKey (/home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/level-packager/node_modules/level-codec/index.js:30:45)
    at /home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/level-packager/node_modules/level-codec/index.js:51:17
```

**Comment by ahdinosaur** [comment]
stopped, deleted all the indexes (all files in `~/.ssb/flume` expect for `log.offset`), restarted, it seems to work meow! :cat:

**Comment by ahdinosaur** [comment]
oh no it came back!

**Comment by mmckegg** [comment]
@ahdinosaur is this related? 

https://github.com/ssbc/scuttlebot/issues/472

**Comment by ahdinosaur** [comment]
@mmckegg yes, i upgraded to the latest `scuttlebot` and that seems to have resolved the issue, yay.
