### ISSUE TITLE
Invalid private message

### ISSUE THREAD

**Issue by arj03** [ssbc/scuttlebot#495]
So I finally figured out why my messages was having trouble getting through, it seems like somehow my sbot managed to create an invalid message. The message in question is:

```
{
  "previous": "%opn96peLQb+rmwOencGZf+4JrlyQrqFPHPlKW8KvBsA=.sha256",
  "sequence": 3447,
  "author": "@6CAxOI3f+LUOVrbAl0IemqiS7ATpQvr9Mdw9LC4+Uv0=.ed25519",
  "timestamp": 1525114200284,
  "hash": "sha256",
  "content": "Lk2gANAtOUJEbjNwY9q4hmV5c5OeErAxpQ4y3Jdbopg8tVC4zJj4WiQSpHDtvqTtJ2gZgy7HWkdbS2XQ8Df8nyYGXdvX4Od5OAXUslIIpPpwGBBw6uCWCi3DIqrjf3MrEUFd86iFupMG1Hnk+F2i0H89dAPtsvgujx/s7maIysH5bU0XuhFyTrfkbUz8CW+29UDEJ1rljk0Yb+wEQ9xfEBuZDMCU5deqSq1R5c7X8ivLowpFP60WXasNEWmXv2P2I7HG8SOlMsV6Cr2odfXuRJU0ZicYjTFR8MPnCRdla3bm75FNJwkclsJTFMYwAYylgjewwRoMvBPTRhjE+7QTGALau+Yfzo5dGCrFUGIM6lKq2RG5+8qOdsXQTbX/MVXZOzoGsEfKLG0+GgbEU8358hHn+4kxS3WzqdB20O3MakXQVXMkjLkHsEB/ilrtLBWDsGmU1kW+9Ep8IFTrvclERUTZonw2ZalNVmU0sR+5tQic/YS0vSdif+fH7Yoos/IWshWehl+bKEwJGcWWfUCQdcVwQTyvnac9Q9lXHsTDf9WaFcCkm4aoKeBlCTkXzmnw2C6DfWDfg+tIqKw07bCXCBdhk3Of+k9YgC5ZHuWBkU0TsO660gV1GKGuNhXa4Tr7D4eNUEGUTXbx9nkSaAWQweGv6DwkiKvjzEFQNXRC2i9L//PsAerK0awUSoLDQR1hab74N6YX+fRxly/0GZ6dUMzHXfpdFDBmqcfJdWW+mpQ8NmkIz/7O2U7jWBhA77XeVyNteabcJwgm2DhQ0CMYOXBjgIVWitX1PzcUsdm38yMvQNcKpLYobVi5CGNfv5Q9jNDAKhzH5TB7rxLUua/n9WK/PzdcX42o8qjvaM64e2zfEAUgdm2wRYcFySUqltjOfZ7y+MNltenM9Y6qPCU1xDlk9lAQpfl95hVGmWmFyoB4Rwn+oq+rKzYDYKhXV5SVPnfdC/zPZUFK14yYyqmCx4S9EsB7Zkv0D0acsg2P8qxjlCms0oTfEZHjWJGaQpFt8W7ctcd+BJZYT4CO4pAMviHBq6q++xLcL8/nMGL9tXr4mhJ4iXL4ae2ncpoDn7q1qyzJSTCm9xoa50fA3iW3owjB31fd+DcYfF6FVn1n1PRhyi/CyZ6Iadt7XUSSgEHIZD9FVc2fhTUMoYb/9eF5lqLzqOA=.box",
  "signature": "xqbBF3kUenOXzrCROUle+4miwopyJwhk6RXFx+msyizEFhPgMnBQzh62162kLi8j938tt2pf9Zi6MgAcQQnEAg==.sig.ed25519"
}
```

I havn't done anything special. This is sbot 11.3 with ssb-keys 7.0.15 and patchbay created the message.

**Comment by dominictarr** [comment]
hmm, seems like it might be related to: https://github.com/ssbc/scuttlebot/issues/493

what error message did you get?

**Comment by dominictarr** [comment]
btw, the last message I have of yours is 
```
{
  "key": "%opn96peLQb+rmwOencGZf+4JrlyQrqFPHPlKW8KvBsA=.sha256",
  "value": {
    "previous": "%K7Q3kOcv/Z3nLM3jsu+mAqtCMDjGWj1wie9O8EdgvZs=.sha256",
    "sequence": 3446,
    "author": "@6CAxOI3f+LUOVrbAl0IemqiS7ATpQvr9Mdw9LC4+Uv0=.ed25519",
    "timestamp": 1525103880932,
    "hash": "sha256",
    "content": {
      "type": "contact",
      "contact": "@MD3RNVfbta1lIVyNWVzHyIazPgFb+1ZAWQ7qzQeU0y4=.ed25519",
      "following": true
    },
    "signature": "o+aAuQ2lZdOqRwSh7RCjxOrSErwNKQNRmvBosZ5QanOfy6bfTbJhltEaHZX4RZxGeaIaTVf25mRFJIp5ezuyBg==.sig.ed25519"
  },
  "timestamp": 1525104904813
}
```
(which is the previous message to that)

**Comment by arj03** [comment]
Exactly thats the last message I have been able to send. I'm getting the error here:

https://github.com/dominictarr/epidemic-broadcast-trees/pull/16

ssb-ebt won't let this message through as it fails ssb-validate:

```
got err { Error: invalid signature
    at Object.exports.checkInvalid (/home/node/.nvm/versions/node/v9.8.0/lib/node_modules/scuttlebot/node_modules/ssb-validate/index.js:116:18)
    at Object.exports.append (/home/node/.nvm/versions/node/v9.8.0/lib/node_modules/scuttlebot/node_modules/ssb-validate/index.js:161:20)
    at reduce (/home/node/.nvm/versions/node/v9.8.0/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/minimal.js:54:15)
    at queue (/home/node/.nvm/versions/node/v9.8.0/lib/node_modules/scuttlebot/node_modules/async-write/index.js:30:31)
    at /home/node/.nvm/versions/node/v9.8.0/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/minimal.js:96:5
    at EventEmitter.queue (/home/node/.nvm/versions/node/v9.8.0/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/minimal.js:88:17)
    at EventEmitter.db.add (/home/node/.nvm/versions/node/v9.8.0/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/index.js:76:8)
    at apply (/home/node/.nvm/versions/node/v9.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc-validation/index.js:173:15)
    at EventEmitter.<anonymous> (/home/node/.nvm/versions/node/v9.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc-validation/index.js:82:14)
    at EventEmitter.hooked [as add] (/home/node/.nvm/versions/node/v9.8.0/lib/node_modules/scuttlebot/node_modules/hoox/index.js:10:15) fatal: true }
```

**Comment by dominictarr** [comment]
@arj03 yeah, I added this as a test case to ssb-validate, and it says invalid signature too. was this created with patchfoo?

**Comment by dominictarr** [comment]
also is this message in your local database?

**Comment by arj03** [comment]
No with patchbay

**Comment by arj03** [comment]
Yes I can see the message just fine :smile:

**Comment by arj03** [comment]
The message it just a completely ordinary message, no attachments or anything.

**Comment by dominictarr** [comment]
@arj03 is this related to https://github.com/ssbc/scuttlebot/issues/493 what version of ssb-keys do you have? what patchbay patchcore version do you have?

**Comment by dominictarr** [comment]
oh I see you mentioned that above

**Comment by arj03** [comment]
Not sure its related to that issue, I just saw the issue and it seemed like something was making my messages take a much longer to get through so I updated ssb-keys.

I'm running latest patchbay from git which is including latest patchcore.

**Comment by arj03** [comment]
The message is for the main net. And to answer @mixmix I can't tomorrow. Its already late here and I have to get up really early tomorrow and will be away the whole day.

**Comment by dominictarr** [comment]
can you create public messages? it seems rather weird that it only affects private messages.

**Comment by dominictarr** [comment]
I was looking at patchbay and noticed that it still uses `ssb-feed` (where as ssb-validate is now used in sbot, thus ebt...)

so this could be a lead
https://github.com/ssbc/patchcore/blob/master/sbot.js#L193-L197

**Comment by dominictarr** [comment]
I wrote some code to try and figure this out,

``` js
var v = require('ssb-validate')
var createFeed = require('ssb-feed/validator')

var invalid = {
  "previous": "%opn96peLQb+rmwOencGZf+4JrlyQrqFPHPlKW8KvBsA=.sha256",
  "sequence": 3447,
  "author": "@6CAxOI3f+LUOVrbAl0IemqiS7ATpQvr9Mdw9LC4+Uv0=.ed25519",
  "timestamp": 1525114200284,
  "hash": "sha256",
  "content": "Lk2gANAtOUJEbjNwY9q4hmV5c5OeErAxpQ4y3Jdbopg8tVC4zJj4WiQSpHDtvqTtJ2gZgy7HWkdbS2XQ8Df8nyYGXdvX4Od5OAXUslIIpPpwGBBw6uCWCi3DIqrjf3MrEUFd86iFupMG1Hnk+F2i0H89dAPtsvgujx/s7maIysH5bU0XuhFyTrfkbUz8CW+29UDEJ1rljk0Yb+wEQ9xfEBuZDMCU5deqSq1R5c7X8ivLowpFP60WXasNEWmXv2P2I7HG8SOlMsV6Cr2odfXuRJU0ZicYjTFR8MPnCRdla3bm75FNJwkclsJTFMYwAYylgjewwRoMvBPTRhjE+7QTGALau+Yfzo5dGCrFUGIM6lKq2RG5+8qOdsXQTbX/MVXZOzoGsEfKLG0+GgbEU8358hHn+4kxS3WzqdB20O3MakXQVXMkjLkHsEB/ilrtLBWDsGmU1kW+9Ep8IFTrvclERUTZonw2ZalNVmU0sR+5tQic/YS0vSdif+fH7Yoos/IWshWehl+bKEwJGcWWfUCQdcVwQTyvnac9Q9lXHsTDf9WaFcCkm4aoKeBlCTkXzmnw2C6DfWDfg+tIqKw07bCXCBdhk3Of+k9YgC5ZHuWBkU0TsO660gV1GKGuNhXa4Tr7D4eNUEGUTXbx9nkSaAWQweGv6DwkiKvjzEFQNXRC2i9L//PsAerK0awUSoLDQR1hab74N6YX+fRxly/0GZ6dUMzHXfpdFDBmqcfJdWW+mpQ8NmkIz/7O2U7jWBhA77XeVyNteabcJwgm2DhQ0CMYOXBjgIVWitX1PzcUsdm38yMvQNcKpLYobVi5CGNfv5Q9jNDAKhzH5TB7rxLUua/n9WK/PzdcX42o8qjvaM64e2zfEAUgdm2wRYcFySUqltjOfZ7y+MNltenM9Y6qPCU1xDlk9lAQpfl95hVGmWmFyoB4Rwn+oq+rKzYDYKhXV5SVPnfdC/zPZUFK14yYyqmCx4S9EsB7Zkv0D0acsg2P8qxjlCms0oTfEZHjWJGaQpFt8W7ctcd+BJZYT4CO4pAMviHBq6q++xLcL8/nMGL9tXr4mhJ4iXL4ae2ncpoDn7q1qyzJSTCm9xoa50fA3iW3owjB31fd+DcYfF6FVn1n1PRhyi/CyZ6Iadt7XUSSgEHIZD9FVc2fhTUMoYb/9eF5lqLzqOA=.box",
  "signature": "xqbBF3kUenOXzrCROUle+4miwopyJwhk6RXFx+msyizEFhPgMnBQzh62162kLi8j938tt2pf9Zi6MgAcQQnEAg==.sig.ed25519"
}

var valid = {
  "key": "%opn96peLQb+rmwOencGZf+4JrlyQrqFPHPlKW8KvBsA=.sha256",
  "value": {
    "previous": "%K7Q3kOcv/Z3nLM3jsu+mAqtCMDjGWj1wie9O8EdgvZs=.sha256",
    "sequence": 3446,
    "author": "@6CAxOI3f+LUOVrbAl0IemqiS7ATpQvr9Mdw9LC4+Uv0=.ed25519",
    "timestamp": 1525103880932,
    "hash": "sha256",
    "content": {
      "type": "contact",
      "contact": "@MD3RNVfbta1lIVyNWVzHyIazPgFb+1ZAWQ7qzQeU0y4=.ed25519",
      "following": true
    },
    "signature": "o+aAuQ2lZdOqRwSh7RCjxOrSErwNKQNRmvBosZ5QanOfy6bfTbJhltEaHZX4RZxGeaIaTVf25mRFJIp5ezuyBg==.sig.ed25519"
  },
  "timestamp": 1525104904813
}

var state = {
  feeds: {}, queue: []
}

state.feeds[invalid.author] = {
  id: invalid.previous,
  timestamp: 1525103880932,
  sequence: 3446,
  queue: []
}

//this throws (as expected)
//v.append(state, null, invalid)

//this also throws.
var f = createFeed({
  getLatest: function (id, cb) {
    console.log('GETLATEST', id)
    cb(null, valid)
  },
  add: function (msg) {
    console.log(msg)
  },
  batch: function (ary, cb) {
    console.log(ary)
  }
}, invalid.author)

f(invalid, function (err) {
  if(err) throw err
})
```
and it looks like this message is invalid in both ssb-feed and ssb-validate... so the question is... how did this message get created?

**Comment by arj03** [comment]
First of all thanks a lot for your help!

I have 4 messages that has not been gossipped to the world because the first is the private message where the signature is wrong. The wierd thing is that I couldn't see any errors as all in patchbay. The only reason why I found out was that messages a day earlier seemed to be slow to propagate, so I was looking at the ssb viewer of my pub to try and figure out when messaging would be propagated. And when I did a direct connect to the pub and it didn't update I knew something was wrong. The logging in ebt was tremendously helpful! Glad I improve it a little bit.

I wrote a small test prog to check all my messages up til the wrong message and they all validate.

I'm going to try and post a new private message and see if I run into the same problem again :crossed_fingers:

**Comment by arj03** [comment]
Hmmm. There is something really wierd in sbot 11.3. If I run the following program on my log on 11.2.2 it works fine:

```
var pull = require('pull-stream')
var v = require('ssb-validate')

require('ssb-client')((err, sbot) => {
  if (err) throw err;

  var state = {
    queue: [],
    feeds: {},
    error: null
  }

  var myid = '@6CAxOI3f+LUOVrbAl0IemqiS7ATpQvr9Mdw9LC4+Uv0=.ed25519'
  
  state.feeds[myid] = null
  
  pull(
    sbot.createUserStream({ id: myid }),
    pull.drain(function (msg) {
      try {
        if (state.feeds[myid] == null) {
          state.feeds[myid] = {
            id: msg.key,
            timestamp: msg.value.timestamp,
            sequence: 1,
            queue: []
          }
          return true
        }
        
        state = v.append(state, null, msg.value)
        if (state.error) {
          console.log(state.error)
          console.log(msg)
          throw("")
        }
      } catch (e) {
        console.log("exception", e)
        console.log(msg)
        throw("")
      }
    }, function() {
      console.log("all good, the log is clean!", state.feeds)
    })
  )
})
```

But with sbot 11.3 it dies with:

```
exception { Error: invalid signature
    at Object.exports.checkInvalid (/home/chrx/dev/validate-me/node_modules/ssb-validate/index.js:116:18)
    at Object.exports.append (/home/chrx/dev/validate-me/node_modules/ssb-validate/index.js:161:20)
    at /home/chrx/dev/validate-me/index.js:38:19
    at /home/chrx/dev/validate-me/node_modules/pull-stream/sinks/drain.js:24:37
    at PacketStreamSubstream.weird.read (/home/chrx/dev/validate-me/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/home/chrx/dev/validate-me/node_modules/packet-stream/index.js:204:12)
    at PacketStream.write (/home/chrx/dev/validate-me/node_modules/packet-stream/index.js:135:41)
    at /home/chrx/dev/validate-me/node_modules/muxrpc/pull-weird.js:56:15
    at /home/chrx/dev/validate-me/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/chrx/dev/validate-me/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11 fatal: true }
{ key: '%HZVnEzm0NgoSVfG0Hx4gMFbMMHhFvhJsG2zK/pijYII=.sha256',
  value: 
   { previous: '%H3MlLmVPVgHU6rBSzautUBZibDttkI+cU4lAFUIM8Ag=.sha256',
     sequence: 2,
     author: '@6CAxOI3f+LUOVrbAl0IemqiS7ATpQvr9Mdw9LC4+Uv0=.ed25519',
     timestamp: 1456154934819,
     hash: 'sha256',
     content: 
      { type: 'post',
        text: 'Testing first mesage',
        channel: 'testing' },
     signature: 'az18LEvCgji1zqpAF/JcTool+y69WhyLVesvWcrnyj5pFJymXKALZ7zUDRuxOcBGr+wU4v6zN/+b3tAYsz+zBg==.sig.ed25519' },
  timestamp: 1525203910565 }

/home/chrx/dev/validate-me/index.js:47
        throw("")
        ^
```

**Comment by arj03** [comment]
And now replication is super smooth as well.

**Comment by arj03** [comment]
This is the message as printed with sbot 11.2.2:

```
{ key: '%HZVnEzm0NgoSVfG0Hx4gMFbMMHhFvhJsG2zK/pijYII=.sha256',
  value: 
   { previous: '%H3MlLmVPVgHU6rBSzautUBZibDttkI+cU4lAFUIM8Ag=.sha256',
     author: '@6CAxOI3f+LUOVrbAl0IemqiS7ATpQvr9Mdw9LC4+Uv0=.ed25519',
     sequence: 2,
     timestamp: 1456154934819,
     hash: 'sha256',
     content: 
      { type: 'post',
        text: 'Testing first mesage',
        channel: 'testing' },
     signature: 'az18LEvCgji1zqpAF/JcTool+y69WhyLVesvWcrnyj5pFJymXKALZ7zUDRuxOcBGr+wU4v6zN/+b3tAYsz+zBg==.sig.ed25519' },
  timestamp: 1525203910565 }
```

Notice the keys are in different order, maybe that's why it fails?

**Comment by arj03** [comment]
Right, reboxValue in secure-scuttlebutt changes the order of the dict ;-)

**Comment by arj03** [comment]
With that change to secure-scuttlebutt things should be working again :rocket:

**Comment by christianbundy** [comment]
@arj03 Does that mean this is ready to close? :tada:
