### ISSUE TITLE
could not retrive msg: NotFoundError: Key not found in database 

### ISSUE THREAD

**Issue by evbogue** [ssbc/scuttlebot#501]
I'm trying to upgrade Decent to latest sbot, and I'm seeing a lot of these errors now. Feeds are loading sometimes, but other times are not. All of the errors are on the server. 

Anyone else seeing these?

```
could not retrive msg: NotFoundError: Key not found in database [@dl9NuaSwZViTMF4OJwQuPhdtzvOt2z2xnTMz8XL45Hs=.ed25519,7]
    at /home/ev/decent/node_modules/level-packager/node_modules/levelup/lib/levelup.js:164:15
    at /home/ev/decent/node_modules/encoding-down/index.js:50:21
could not retrive msg: NotFoundError: Key not found in database [@dl9NuaSwZViTMF4OJwQuPhdtzvOt2z2xnTMz8XL45Hs=.ed25519,7]
    at /home/ev/decent/node_modules/level-packager/node_modules/levelup/lib/levelup.js:164:15
    at /home/ev/decent/node_modules/encoding-down/index.js:50:21
could not retrive msg: NotFoundError: Key not found in database [@dl9NuaSwZViTMF4OJwQuPhdtzvOt2z2xnTMz8XL45Hs=.ed25519,7]
    at /home/ev/decent/node_modules/level-packager/node_modules/levelup/lib/levelup.js:164:15
    at /home/ev/decent/node_modules/encoding-down/index.js:50:21
could not retrive msg: NotFoundError: Key not found in database [@5yP0SoZVkMIXUQcL7nPGsw6yYIxE23UBd+rLO+6OSWc=.ed25519,5]
    at /home/ev/decent/node_modules/level-packager/node_modules/levelup/lib/levelup.js:164:15
    at /home/ev/decent/node_modules/encoding-down/index.js:50:21
```

**Comment by evbogue** [comment]
I'm not seeing this error anymore. I think it was a bad leveldb build.
