### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by ArbazYousuf** [ssbc/scuttlebot#517]
match is undefined on path "/scuttlebot/node_modules/ip/lib/ip.js"
on line number 262 addr.match

**Comment by cryptix** [comment]
Hmm.. Haven't seen this one. How did you produce this error?

In any case we maybe should upgrade npm:ip. Current version is 1.1.5 and sbot is using 0.3. No idea what the breaking changes are, though.

**Comment by cryptix** [comment]
Okay.. than it smells like a recent change here Passes something that wasn’t error-checked down to isPrivate...

A full stack trace would be nice

**Comment by kaotisk-hund** [comment]
How can I generate this?

**Comment by cryptix** [comment]
checking again, the only place where I see `isPrivate` being used is in [inviate.create](https://github.com/ssbc/scuttlebot/blob/a2f5a2c529cc7a14d057e9e02e41f0d8ed52b9fe/plugins/invite.js#L79) so that makes it clear that this issue is about generating invites...

I hate to say it but _tests are passing_. I wonder what wrong/missing assumption there is though...

Can you tell me more about your deployment and how you trigger the creation?
Also: maybe your sbot is running in an IPv6 only setting?

**Comment by kaotisk-hund** [comment]
When I click to get the invite and then I get this message in my browser:
TypeError: Cannot read property 'match' of undefined
   at Object.isPrivate (/usr/src/app/node_modules/scuttlebot/node_modules/ip/lib/ip.js:262:14)
   at Object.<anonymous> (/usr/src/app/node_modules/scuttlebot/plugins/invite.js:71:40)
   at apply (/usr/src/app/node_modules/muxrpc-validation/index.js:173:15)
   at Object.<anonymous> (/usr/src/app/node_modules/muxrpc-validation/index.js:82:14)
   at Object.hooked (/usr/src/app/node_modules/hoox/index.js:10:15)
   at /usr/src/app/dist/index.js:98:16
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)

**Comment by cryptix** [comment]
okay, yes. This looks like what I expected.

> I ran it with docker, 

I can't tell you how to patch a docker image. Never really used it, sorry.

As a workaround: What you could do is to use the `allowPrivate` config or start it with `sbot server --allowPrivate` and than replace the `host:port` in `host:port:@pubkey.ed25510~invite` with the reachable address of the pub (ip or domain).
