### ISSUE TITLE
Error: wrong protocol/version

### ISSUE THREAD

**Issue by bugant** [ssbc/scuttlebot#549]
I just set up my Pub yesterday and I'm new to sbot, but I noticed this mornign the server had some of logs for the following error:

```
server error, from net:::ffff:104.131.167.125:19001~shs:
Error: wrong protocol/version
    at Object.cb (/opt/scuttlebot/.nvm/versions/node/v8.12.0/lib/node_modules/scuttlebot/node_modules/secret-handshake/protocol.js:86:30)
    at drain (/opt/scuttlebot/.nvm/versions/node/v8.12.0/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:39:14)
    at more (/opt/scuttlebot/.nvm/versions/node/v8.12.0/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:55:13)
    at /opt/scuttlebot/.nvm/versions/node/v8.12.0/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:66:9
    at /opt/scuttlebot/.nvm/versions/node/v8.12.0/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:20:7
    at drain (/opt/scuttlebot/.nvm/versions/node/v8.12.0/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/opt/scuttlebot/.nvm/versions/node/v8.12.0/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:150:5)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)```

Is it OK?

**Comment by bugant** [comment]
It happens quite a lot, but could very likely be due to scanners, maybe this can be a warning instead of an error.

**Comment by austinfrey** [comment]
just for others who may run into this. I sometimes run into this when I'm trying to run `sbot` on a testnet, but it tries to make a connection with a different `sbot` instance in my LAN, but that instance is on the ssb main network, thus mismatched caps keys. the fix for me was to delete the `gossip.json` file from my `.ssb-testnet` directory and turn off any other local 'sbot' instances.
