### ISSUE TITLE
Tests fails in master

### ISSUE THREAD

**Issue by arj03** [ssbc/scuttlebot#567]
not ok 6 has one ws remote
  ---
    operator: equal
    expected: 1
    actual:   0
    at: <anonymous> (/home/chrx/dev/scuttlebot/test/bin.js:215:7)
    stack: |-
      Error: has one ws remote
          at Test.assert [as _assert] (/home/chrx/dev/scuttlebot/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/chrx/dev/scuttlebot/node_modules/tape/lib/test.js:76:32)
          at Test.equal (/home/chrx/dev/scuttlebot/node_modules/tape/lib/test.js:384:10)
          at Test.bound [as equal] (/home/chrx/dev/scuttlebot/node_modules/tape/lib/test.js:76:32)
          at /home/chrx/dev/scuttlebot/test/bin.js:215:7
          at /home/chrx/dev/scuttlebot/test/bin.js:62:24
          at /home/chrx/dev/scuttlebot/test/bin.js:202:7
          at ChildProcess.exithandler (child_process.js:280:7)
          at ChildProcess.emit (events.js:182:13)
          at maybeClose (internal/child_process.js:962:16)
  ...
/home/chrx/dev/scuttlebot/node_modules/multiserver-address/index.js:18
    return e.map(function (e) {
             ^

TypeError: Cannot read property 'map' of undefined
    at /home/chrx/dev/scuttlebot/node_modules/multiserver-address/index.js:18:14
    at Array.map (<anonymous>)
    at Object.exports.encode (/home/chrx/dev/scuttlebot/node_modules/multiserver-address/index.js:17:15)
    at /home/chrx/dev/scuttlebot/test/bin.js:216:21
    at /home/chrx/dev/scuttlebot/test/bin.js:62:24
    at /home/chrx/dev/scuttlebot/test/bin.js:202:7
    at ChildProcess.exithandler (child_process.js:280:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by cryptix** [comment]
Hmmm might get fixed by #566

**Comment by arj03** [comment]
Using ssb-ws 3.0.0 works. It's just that master is referring to a non-existing 3.0.1 version.

**Comment by dominictarr** [comment]
I published a 3.0.1, it's on the v3 branch on github, btw

**Comment by arj03** [comment]
But not on npm?

**Comment by dominictarr** [comment]
npm is telling me it is on npm:
```
> npm show ssb-ws

 
{ name: 'ssb-ws',
  description: 'websocket & http server for ssb',
  'dist-tags': { latest: '3.0.2' },
  versions: 
   [ '0.0.1',
     '0.0.2',
     '0.0.3',
     '0.0.4',
     '0.1.0',
     '0.1.1',
     '0.1.2',
     '0.1.3',
     '0.2.0',
     '0.3.0',
     '0.3.1',
     '0.3.2',
     '0.3.3',
     '0.4.0',
     '0.4.2',
     '0.4.3',
     '0.4.4',
     '0.5.0',
     '0.5.1',
     '0.5.2',
     '0.5.3',
     '0.5.4',
     '0.6.0',
     '0.6.1',
     '0.6.2',
     '0.7.0',
     '0.7.1',
     '1.0.0',
     '1.0.1',
     '1.0.2',
     '1.0.3',
     '2.0.0',
     '2.1.0',
     '2.1.1',
     '3.0.0',
     '3.0.2',
     '4.0.0',
     '4.0.1' ],
//snip...
}
```

**Comment by dominictarr** [comment]
oh hang on! maybe I unpublished it? anyway, there is an 3.0.2 now

**Comment by dominictarr** [comment]
(I was confused by the output of npm show, because it showed a created time for 3.0.1
```
   '2.1.1': '2018-04-11T02:48:39.602Z',
     '3.0.0': '2018-10-11T05:53:03.573Z',
     '4.0.0': '2018-10-27T11:37:56.063Z',
     '4.0.1': '2018-10-29T00:10:30.543Z',
     '3.0.1': '2018-10-30T02:50:59.634Z',
     '3.0.2': '2018-11-01T07:08:02.009Z' },
```
