### ISSUE TITLE
Gossip has stopped working

### ISSUE THREAD

**Issue by christianbundy** [ssbc/scuttlebot#579]
I'm having an issue where gossip isn't happening no matter how long I leave Scuttlebot running. On 13.2.0 I was seeing #578, but even after downgrading to 13.0.3 the output of `sbot status` shows `gossip: {}` and I haven't been able to receive any messages for about 9 hours. I've tried ^12.0.0 and it said "Error: listen EADDRINUSE :::8989", and ^11.0.0 had the same behavior as 13.2.0 and 13.0.3. Weird.

Has anyone else been having problems? I'm seeing issues with my global `sbot`, Patchbay, and Patchwork. I've tried restarting my machine but it doesn't seem to fix anything. These are the software upgrades I did today, just in case one of these may be misbehaving:

```
[2018-11-25 09:35] [PACMAN] Running 'pacman -Syu'
[2018-11-25 09:35] [PACMAN] synchronizing package lists
[2018-11-25 09:35] [PACMAN] starting full system upgrade
[2018-11-25 09:36] [ALPM] transaction started
[2018-11-25 09:36] [ALPM] upgraded bind-tools (9.13.3-3 -> 9.13.4-1)
[2018-11-25 09:36] [ALPM] upgraded bind (9.13.3-3 -> 9.13.4-1)
[2018-11-25 09:36] [ALPM] upgraded libwmf (0.2.8.4-14 -> 0.2.10-1)
[2018-11-25 09:36] [ALPM] upgraded v4l-utils (1.16.1-1 -> 1.16.2-1)
[2018-11-25 09:36] [ALPM] transaction completed
[2018-11-25 09:36] [ALPM] running 'gdk-pixbuf-query-loaders.hook'...
[2018-11-25 09:36] [ALPM] running 'gtk-update-icon-cache.hook'...
[2018-11-25 09:36] [ALPM] running 'systemd-daemon-reload.hook'...
[2018-11-25 09:36] [ALPM] running 'systemd-sysusers.hook'...
[2018-11-25 09:36] [ALPM] running 'systemd-tmpfiles.hook'...
[2018-11-25 09:36] [ALPM] running 'systemd-udev-reload.hook'...
[2018-11-25 09:36] [ALPM] running 'systemd-update.hook'...
[2018-11-25 09:36] [ALPM] running 'update-desktop-database.hook'...
[2018-11-25 17:06] [PACKAGEKIT] synchronizing package lists
[2018-11-25 17:06] [PACKAGEKIT] synchronizing package lists
[2018-11-25 19:32] [PACMAN] Running 'pacman -Syu'
[2018-11-25 19:32] [PACMAN] synchronizing package lists
[2018-11-25 19:32] [PACMAN] starting full system upgrade
[2018-11-25 19:34] [ALPM] transaction started
[2018-11-25 19:34] [ALPM] upgraded gupnp-av (0.12.10-2 -> 0.12.11-1)
[2018-11-25 19:34] [ALPM] upgraded libphonenumber (8.9.12-3 -> 8.10.1-1)
[2018-11-25 19:34] [ALPM] upgraded linux (4.19.2.arch1-1 -> 4.19.4.arch1-1)
[2018-11-25 19:34] [ALPM] upgraded linux-docs (4.19.2.arch1-1 -> 4.19.4.arch1-1)
[2018-11-25 19:34] [ALPM] upgraded linux-headers (4.19.2.arch1-1 -> 4.19.4.arch1-1)
[2018-11-25 19:34] [ALPM] upgraded pipewire (0.2.3+17+g10ce1a02-1 -> 0.2.4-1)
[2018-11-25 19:34] [ALPM] transaction completed
[2018-11-25 19:34] [ALPM] running '60-linux.hook'...
[2018-11-25 19:35] [ALPM] running '90-linux.hook'...
[2018-11-25 19:35] [ALPM-SCRIPTLET] ==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img
[2018-11-25 19:35] [ALPM-SCRIPTLET] ==> Starting build: 4.19.4-arch1-1-ARCH
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [base]
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [udev]
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [autodetect]
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [modconf]
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [block]
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [filesystems]
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [keyboard]
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [fsck]
[2018-11-25 19:35] [ALPM-SCRIPTLET] ==> Generating module dependencies
[2018-11-25 19:35] [ALPM-SCRIPTLET] ==> Creating gzip-compressed initcpio image: /boot/initramfs-linux.img
[2018-11-25 19:35] [ALPM-SCRIPTLET] ==> Image generation successful
[2018-11-25 19:35] [ALPM-SCRIPTLET] ==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'fallback'
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-fallback.img -S autodetect
[2018-11-25 19:35] [ALPM-SCRIPTLET] ==> Starting build: 4.19.4-arch1-1-ARCH
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [base]
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [udev]
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [modconf]
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [block]
[2018-11-25 19:35] [ALPM-SCRIPTLET] ==> WARNING: Possibly missing firmware for module: aic94xx
[2018-11-25 19:35] [ALPM-SCRIPTLET] ==> WARNING: Possibly missing firmware for module: wd719x
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [filesystems]
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [keyboard]
[2018-11-25 19:35] [ALPM-SCRIPTLET]   -> Running build hook: [fsck]
[2018-11-25 19:35] [ALPM-SCRIPTLET] ==> Generating module dependencies
[2018-11-25 19:35] [ALPM-SCRIPTLET] ==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-fallback.img
[2018-11-25 19:35] [ALPM-SCRIPTLET] ==> Image generation successful
[2018-11-25 19:35] [ALPM] running 'systemd-update.hook'...
```

I think the problem started after the upgrade 09:36, but I've included the later upgrade just in case.

**Comment by christianbundy** [comment]
Confirmed, the first post that failed to replicate started at 11:02.

**Comment by christianbundy** [comment]
Weird, I just checked `~/.ssb/gossip.json` and it looks completely empty (`[]`). I went through my command history and can verify that I haven't touched it, so either a rogue program on my system replaced the file with an empty array or we have a bug somewhere that clears out the gossip file.

Any thoughts on where to start debugging?

**Comment by christianbundy** [comment]
I've copied over an old `gossip.json` file but it just errors out with:

```
Error: not a valid address:{"host":"ssb.ekata.social","port":8008,"key":"@FJDMuATvh0a3qIcIPcstUANVIj362fWkYCG5bnkZ5nA=.ed25519","source":"stored","announcers":610,"duration":{"mean":0,"stdev":0,"count":2,"sum":0,"sqsum":0},"stateChange":1537402489243,"error":"Error: connect ETIMEDOUT 62.151.177.86:8008\n    at Object._errnoException (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)","failure":2}
    at Object.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/plugins/gossip/index.js:222:17)
    at apply (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/muxrpc-validation/index.js:173:15)
    at Object.add (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/muxrpc-validation/index.js:62:14)
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/plugins/gossip/index.js:356:20
    at Array.forEach (<anonymous>)
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/plugins/gossip/index.js:352:13
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/atomic-file/index.js:21:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by christianbundy** [comment]
I've just tried spinning up Patchwork to follow a pub, and while everything *seemed* fine from my side I'm not actually receiving the message from the pub that they followed me back. Also, my gossip file seems to just revert back to `[]` every time that I start Scuttlebot.

**Comment by christianbundy** [comment]
Here's what my Patchwork output looks like when trying to join pubs. I'm unclear on why, but it looks like every address is now "not valid":

```

> ssb-patchwork@3.11.0 start /home/christianbundy/src/ssbc/patchwork
> electron index.js

{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3, global: true },
  connections: 
   { incoming: { net: [Array], dht: [Array] },
     outgoing: { net: [Array], dht: [Array] } },
  path: '/home/christianbundy/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: [],
  configs: [ '/home/christianbundy/.ssb/config' ],
  config: '/home/christianbundy/.ssb/config' }
ssb-friends: createFriendStream legacy api used
%cssb:dht-invite %cstart()%c +0ms color: #FF00CC color: inherit color: #FF00CC
Error: not a valid address:{"host":"ssb.ekata.social","port":8008,"key":"@FJDMuATvh0a3qIcIPcstUANVIj362fWkYCG5bnkZ5nA=.ed25519","source":"stored","announcers":610,"duration":{"mean":0,"stdev":0,"count":2,"sum":0,"sqsum":0},"stateChange":1537402489243,"error":"Error: connect ETIMEDOUT 62.151.177.86:8008\n    at Object._errnoException (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)","failure":2}
    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/@staltz/sbot-gossip/index.js:276:21)
    at apply (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:173:15)
    at Object.add (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:62:14)
    at /home/christianbundy/src/ssbc/patchwork/node_modules/@staltz/sbot-gossip/index.js:435:20
    at Array.forEach (<anonymous>)
    at /home/christianbundy/src/ssbc/patchwork/node_modules/@staltz/sbot-gossip/index.js:428:13
    at /home/christianbundy/src/ssbc/patchwork/node_modules/@staltz/sbot-gossip/node_modules/atomic-file/index.js:21:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
/usr/lib/node_modules/git-ssb/node_modules/git-ssb-web/server.js:19
  if (err) throw err
           ^

Error: could not connect to sbot
    at /usr/lib/node_modules/git-ssb/node_modules/ssb-client/index.js:93:23
    at next (/usr/lib/node_modules/git-ssb/node_modules/multiserver/compose.js:24:14)
    at /usr/lib/node_modules/git-ssb/node_modules/multiserver/compose.js:34:9
    at _cb (/usr/lib/node_modules/git-ssb/node_modules/multiserver/plugins/shs.js:28:20)
    at /usr/lib/node_modules/git-ssb/node_modules/secret-handshake/protocol.js:115:22
    at /usr/lib/node_modules/git-ssb/node_modules/pull-handshake/index.js:10:5
    at /usr/lib/node_modules/git-ssb/node_modules/pull-handshake/index.js:23:13
    at callback (/usr/lib/node_modules/git-ssb/node_modules/pull-pushable/index.js:81:7)
    at drain (/usr/lib/node_modules/git-ssb/node_modules/pull-pushable/index.js:68:39)
  Error: stream ended with:64 but wanted:80
    at drain (/usr/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:43:26)
    at /usr/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:63:18
    at /usr/lib/node_modules/git-ssb/node_modules/pull-reader/index.js:20:7
    at drain (/usr/lib/node_modules/git-ssb/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/usr/lib/node_modules/git-ssb/node_modules/stream-to-pull-stream/index.js:162:5)
    at Socket.emit (events.js:187:15)
    at TCP._handle.close (net.js:606:12)
ssb-friends: stream legacy api used
{ message: 'not a valid address:{"host":"qypea1.dyndns.info","port":8008,"key":"@1sw77BWBwCzMlQuPG0YkZw8uiHRpEeBe5uLjzXGY36w=.ed25519"}',
  name: 'Error',
  stack: 'Error: not a valid address:{"host":"qypea1.dyndns.info","port":8008,"key":"@1sw77BWBwCzMlQuPG0YkZw8uiHRpEeBe5uLjzXGY36w=.ed25519"}\n    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/@staltz/sbot-gossip/index.js:276:21)\n    at apply (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:173:15)\n    at Object.add (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:62:14)\n    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/@staltz/sbot-gossip/index.js:217:16)\n    at apply (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:173:15)\n    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:82:14)\n    at Object.hooked (/home/christianbundy/src/ssbc/patchwork/node_modules/hoox/index.js:10:15)\n    at Object.localCall (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc/local-api.js:31:29)\n    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc/local-api.js:37:22)\n    at Object.request (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc/stream.js:46:17)' }
{ message: 'not a valid address:{"host":"zie.one","port":8008,"key":"@tgzHDm9HEN0k5wFRLFmNPyGZYNF/M5KpkZqCRhgowVE=.ed25519"}',
  name: 'Error',
  stack: 'Error: not a valid address:{"host":"zie.one","port":8008,"key":"@tgzHDm9HEN0k5wFRLFmNPyGZYNF/M5KpkZqCRhgowVE=.ed25519"}\n    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/@staltz/sbot-gossip/index.js:276:21)\n    at apply (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:173:15)\n    at Object.add (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:62:14)\n    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/@staltz/sbot-gossip/index.js:217:16)\n    at apply (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:173:15)\n    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:82:14)\n    at Object.hooked (/home/christianbundy/src/ssbc/patchwork/node_modules/hoox/index.js:10:15)\n    at Object.localCall (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc/local-api.js:31:29)\n    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc/local-api.js:37:22)\n    at Object.request (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc/stream.js:46:17)' }
{ message: 'not a valid address:{"host":"zie.one","port":8008,"key":"@tgzHDm9HEN0k5wFRLFmNPyGZYNF/M5KpkZqCRhgowVE=.ed25519"}',
  name: 'Error',
  stack: 'Error: not a valid address:{"host":"zie.one","port":8008,"key":"@tgzHDm9HEN0k5wFRLFmNPyGZYNF/M5KpkZqCRhgowVE=.ed25519"}\n    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/@staltz/sbot-gossip/index.js:276:21)\n    at apply (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:173:15)\n    at Object.add (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:62:14)\n    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/@staltz/sbot-gossip/index.js:217:16)\n    at apply (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:173:15)\n    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc-validation/index.js:82:14)\n    at Object.hooked (/home/christianbundy/src/ssbc/patchwork/node_modules/hoox/index.js:10:15)\n    at Object.localCall (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc/local-api.js:31:29)\n    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc/local-api.js:37:22)\n    at Object.request (/home/christianbundy/src/ssbc/patchwork/node_modules/muxrpc/stream.js:46:17)' }
```

I think the git-ssb error can safely be ignored, but I'm concerned at why my `gossip.json` file was overwritten and all peers now have invalid hosts.

**Comment by staltz** [comment]
Are you using my sbot-gossip forked plugin?

**Comment by christianbundy** [comment]
@staltz  I'm using it above when using Patchwork, but I have the same issue when using `sbot server`. As far as I can tell, this issue is affecting Patchwork, Patchbay, and every version of Scuttlebot I've tried. It seems like a system issue, but after rolling back my most recent upgrade (bind, bind-tools, and v4l-utils) I'm still having the issue.

I think this is what's happening:

1. Scuttlebot is loading the gossip file.
2. The "not a valid address" error is thrown (?!).
3.  `[]` is used as a default peer list.
4. The `gossip.json` file is [overwritten](https://github.com/ssbc/scuttlebot/blob/master/plugins/gossip/index.js#L394) with the empty array.

Here's my `gossip.json`, although GitHub forced me to zip it before uploading: [gossip.json.zip](https://github.com/ssbc/scuttlebot/files/2616214/gossip.json.zip)

**Comment by christianbundy** [comment]
Strangely enough, it looks like scuttlebot-release does *not* have this problem, which makes me wonder whether it's deep dependency issue somewhere.

**Comment by cryptix** [comment]
Just to ignore the potential sheduler issue: can you use `sbot gossip.connect host:port:pubKey` to make a manual connection?

**Comment by christianbundy** [comment]
@cryptix That worked! Here's the command I used:

```sh
< ~/.ssb/gossip.json | jq '.[] | "\(.host):\(.port):\(.key)"' | xargs -L 1 timeout 10s sbot gossip.connect
```

I thought `sbot gossip.reconnect` would manually make the connection(s), but I've run it dozens of times and it doesn't seem to be doing anything. I'm lucky that I had a backup `gossip.json`.

**Comment by cryptix** [comment]
> I thought sbot gossip.reconnect would manually make the connection(s) ...

I feel you. I would think reconnect has the same problem the sheduler has.

**Comment by dominictarr** [comment]
This must be related to that in 13 peers are represented with multiserver addresses, but in the old gossip.json files they won't be like that.

**Comment by dominictarr** [comment]
plugins/gossip/index just trusts gossip.json file, so it was probably loading internal state that was no longer valid... (but could easily be translated)
I also noticed there are TWO bits that load the gossip file!
https://github.com/ssbc/scuttlebot/blame/master/plugins/gossip/index.js#L88
basically that filter in the second one should be moved into the first one, and if the peer is missing and `address` property it should be reconstructed, like this: https://github.com/ssbc/scuttlebot/blame/master/plugins/gossip/index.js#L236-L238

**Comment by christianbundy** [comment]
> in the old gossip.json files they won't be like that

Oh, do you think this could be caused by switching between two versions of Scuttlebot? I've only been on 13.x.x, so if there's a backward-incompatibility I think that would be unexpected.

**Comment by dominictarr** [comment]
yes sounds like it, when you call `gossip.add(peer)` it transforms it to be 13 style, but it needs to preserve what 12 needs.

**Comment by dominictarr** [comment]
though, it should pull in peers from the pub messages... hmm

**Comment by christianbundy** [comment]
It's probably also worth asking: what's the difference between "13 style" gossip data and the previous default? Did we move from `{ host, port, key }` to a full multiserver address?
