### ISSUE TITLE
weird bug in using invite code... fixed it self after a restart

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttlebot#62]
@NHQ was helping me test the latest scuttlebot and we got a weird error:

```
<jjjohnny_> Error: async call failed
<jjjohnny_>     at /home/johnny/projects/scuttlebot/bin.js:152:23
<jjjohnny_>     at Array.requests.(anonymous function) (/home/johnny/projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:153:9)
<jjjohnny_>     at onRequest (/home/johnny/projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:20:27)
<jjjohnny_>     at Object.p.write (/home/johnny/projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:173:33)
<jjjohnny_>     at /home/johnny/projects/scuttlebot/node_modules/muxrpc/pull-weird.js:45:15
<jjjohnny_>     at loop (/home/johnny/projects/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33)
<jjjohnny_>     at /home/johnny/projects/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/throughs.js:97:9
<jjjohnny_>     at /home/johnny/projects/scuttlebot/node_modules/pull-stream/throughs.js:97:9
<jjjohnny_>     at /home/johnny/projects/scuttlebot/node_modules/pull-stream/throughs.js:21:7
<jjjohnny_>   Error: invite not accepted
<jjjohnny_>     at /home/johnny/projects/scuttlebot/plugins/invite.js:151:26
<jjjohnny_>     at requests.(anonymous function) (/home/johnny/projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:153:9)
<jjjohnny_>     at /home/johnny/projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:184:58
<jjjohnny_>     at Array.forEach (native)
<jjjohnny_>     at Object.p.destroy (/home/johnny/projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:184:16)
<jjjohnny_>   Error: unexpected end of parent stream
<domanic> ah okay
<jjjohnny_>     at Object.p.destroy (/home/johnny/projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:181:15)
<jjjohnny_>     at Object.p.write (/home/johnny/projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:171:24)
<jjjohnny_>     at source (/home/johnny/projects/scuttlebot/node_modules/muxrpc/pull-weird.js:34:15)
<jjjohnny_>     at /home/johnny/projects/scuttlebot/node_modules/muxrpc/node_modules/pull-goodbye/endable.js:6:7
<jjjohnny_>     at /home/johnny/projects/scuttlebot/node_modules/pull-stream/throughs.js:13:5
<jjjohnny_>     at /home/johnny/projects/scuttlebot/node_modules/pull-inactivity/node_modules/pull-stream/throughs.js:123:12
<jjjohnny_>     at cancel (/home/johnny/projects/scuttlebot/node_modules/pull-inactivity/node_modules/pull-abortable/index.js:13:5)
<jjjohnny_>     at Function.reader.abort (/home/johnny/projects/scuttlebot/node_modules/pull-inactivity/node_modules/pull-abortable/index.js:47:5)
<jjjohnny_>     at abort (/home/johnny/projects/scuttlebot/node_modules/pull-inactivity/index.js:32:17)
<jjjohnny_>     at null.<anonymous> (/home/johnny/projects/scuttlebot/node_modules/pull-inactivity/index.js:39:7)
```

updating the server to the latest code and restarting fixed it. I'm not sure what it was but leaving this here incase it happens again.

**Comment by dominictarr** [comment]
which invite code did you use? my server is down because my credit stuff was wrong after i lost my credit card recently. this is back up now... can you try again?

**Comment by pfraze** [comment]
i used what was in the readme. if your instance was down, then i wonder if the connection failure event wasnt captured and it just timed out

**Comment by dominictarr** [comment]
hmm, I think that should have had a ENCONNREFUSED error, we should add tests for this.

**Comment by evbogue** [comment]
I've never seen this.
