### ISSUE TITLE
Noisy error output: "Error replicating with...", "client is blocked", etc.

### ISSUE THREAD

**Issue by dpriskorn** [ssbc/scuttlebot#733]
Hi. Got this error today. No idea if it influences functionality:
```
info @JxB SSB- 165.22.145.38:8008:@ennK62KwH3KfitZAgeJMwjlD2h4Z2UIycuVCxPeaUFI=.ed25519 PEER JOINED 
Error replicating with @ennK62KwH3KfitZAgeJMwjlD2h4Z2UIycuVCxPeaUFI=.ed25519:
   Error: method:createHistoryStream is not in list of allowed methods
    at Function.perms.pre (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/muxrpc/permissions.js:88:14)
    at Object.<anonymous> (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/muxrpc/local-api.js:35:21)
    at PacketStreamSubstream.stream.read (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/muxrpc/stream.js:69:23)
    at PacketStream._onstream (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/packet-stream/index.js:228:11)
    at PacketStream.write (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/packet-stream/index.js:135:41)
    at /home/node/.npm-global/lib/node_modules/ssb-room/node_modules/muxrpc/pull-weird.js:56:15
    at /home/node/.npm-global/lib/node_modules/ssb-room/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/node/.npm-global/lib/node_modules/ssb-room/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/pull-reader/index.js:39:14)

```

**Comment by timjrobinson** [comment]
I just installed the latest ssb server with `npm install -g ssb-server@latest` with NodeJS v10 and am seeing this error too. Server is not starting. I'm running https://hub.docker.com/repository/docker/timjrobinson/ssb-pub which is based off https://github.com/timjrobinson/ssb-pub with the only changes from @ahdinosaur 's version being using the latest version of ssb-server and NodeJS 10 instead of 8.

**Comment by clehner** [comment]
"Error replicating with ..." errors can be safely ignored. Although it is odd that it rejects `createHistoryStream` - maybe it is just doesn't do legacy gossip.
I am considering this error output noisy and misleading because it leads people to think it may be a problem. I'm updating the issue title to reflect that.
