### ISSUE TITLE
remote error on blob download should cleanup and stop requesting from the errored peer

### ISSUE THREAD

**Issue by pfrazee** [ssbc/scuttlebot#90]
there's currently a bug in the blobs plugin that causes a successfully-found blob to get mismapped. the searcher sees that a peer has the blob, then mismaps and (as a result) requests the wrong blob from the peer. 

i'm going to figure out that mismap next, but the larger issue is what happens on this mismap. a download is attempted, and the other peer fails to get the file. this causes the following to happen on the receiving end:
- a tempfile is allocated
- the file-read error makes its way to the receiving peer
- for some reason, the content digest is still computed (and of course found to be incorrect)
- the download aborts, but...
  - the tempfile is not destroyed (related to #89)
  - the download is re-queued without removing that peer, so it happens repeatedly

here's the log output:

```
info 64Fm BLOB  want "/ZrDz5KILJSmJ/BMyt2KTR8bc8vNXLMZAQaoRSdWvbY=.blake2s"
QUERY FINISHED kIetR4xx26Q2M62vG0tNrptJDFnxP0SexLHaOIkyy08=.blake2s [ true ]
info 64Fm BLOB kIetR4xx26Q2M62vG0tNrptJDFnxP0SexLHaOIkyy08=.blake2s found
  "Cfwc/sY2eTHDVfFJO7RWToGib2JAeBvDppXPamDE5Js=.blake2s"
QUERY FINISHED TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s [ false ]
download wantlist is... [ { id: 'Cfwc/sY2eTHDVfFJO7RWToGib2JAeBvDppXPamDE5Js=.blake2s',
    waiting: [ [Function], [Function], [Function] ],
    state: 'ready',
    has: 
     { 'kIetR4xx26Q2M62vG0tNrptJDFnxP0SexLHaOIkyy08=.blake2s': true,
       'TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s': false } } ]
info 64Fm BLOB kIetR4xx26Q2M62vG0tNrptJDFnxP0SexLHaOIkyy08=.blake2s downloading
  "Cfwc/sY2eTHDVfFJO7RWToGib2JAeBvDppXPamDE5Js=.blake2s"
Error: could not write to tmpfile
    at /home/pfraze/scuttlebot/node_modules/multiblob/index.js:79:29
    at done (/home/pfraze/scuttlebot/node_modules/stream-to-pull-stream/index.js:21:11)
    at /home/pfraze/scuttlebot/node_modules/stream-to-pull-stream/index.js:50:16
    at /home/pfraze/scuttlebot/node_modules/multiblob/node_modules/pull-stream/throughs.js:126:7
    at /home/pfraze/scuttlebot/node_modules/pull-stream/throughs.js:21:7
    at Object.weird.read (/home/pfraze/scuttlebot/node_modules/muxrpc/pull-weird.js:24:7)
    at onStream (/home/pfraze/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:86:14)
    at Object.p.write (/home/pfraze/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:174:33)
    at /home/pfraze/scuttlebot/node_modules/muxrpc/pull-weird.js:45:15
  Error: ENOENT, open '/Users/paulfrazee/.ssb/blobs/blake2s/09/fc1cfec6367931c355f1493bb4564e81a26f6240781bc3a695cf6a60c4e49b'
Error: actual hash:aSF6MHmQgJThESHQQjVKfB9VtkgsoaUeGyUN/R7Q7vk=.blake2s did not match expected hash:Cfwc/sY2eTHDVfFJO7RWToGib2JAeBvDppXPamDE5Js=.blake2s
    at /home/pfraze/scuttlebot/node_modules/multiblob/index.js:82:23
    at done (/home/pfraze/scuttlebot/node_modules/stream-to-pull-stream/index.js:21:11)
    at WriteStream.onClose (/home/pfraze/scuttlebot/node_modules/stream-to-pull-stream/index.js:28:16)
    at WriteStream.EventEmitter.emit (events.js:92:17)
    at fs.js:1601:14
    at Object.oncomplete (fs.js:107:15)
```

**Comment by evbogue** [comment]
I never seen this, so assuming it was fixed in ssb-blobs 2
