### ISSUE TITLE
after suspend, gossip stops making new connections

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#93]
i've observed this on my mac laptop. if the system suspends while sbot is running, sbot won't resume gossip on wake-up.

here are the tail of the logs:

```
info kIet SBOT 284 connect
  {
    "host": "176.58.117.63",
    "port": 2000,
    "time": {
      "connect": 1421999525938,
      "attempt": 1422010336295
    },
    "connected": true,
    "id": "TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s",
    "failure": 0
  }
warn kIet SBOT 284 unauthed
  Error: connect ENETUNREACH
      at errnoException (net.js:904:11)
      at connect (net.js:766:19)
      at net.js:845:9
      at dns.js:72:18
      at process._tickCallback (node.js:419:13)
info kIet SBOT 284 disconnect 
warn kIet SBOT 283 unauthed
  Error: connect ENETUNREACH
      at errnoException (net.js:904:11)
      at connect (net.js:766:19)
      at net.js:845:9
      at asyncCallback (dns.js:68:16)
      at Object.onanswer [as oncomplete] (dns.js:121:9)
info kIet SBOT 283 disconnect 
info kIet SBOT 285 connect
  {
    "host": "176.58.117.63",
    "port": 2000,
    "time": {
      "connect": 1421999525938,
      "attempt": 1422010339483
    },
    "connected": true,
    "id": "TNn7v0MsAs8OpQnyRwtsMeROVWGlKnS/ItX966PAWjI=.blake2s",
    "failure": 1
  }
warn kIet SBOT 285 unauthed
  Error: connect ENETUNREACH
      at errnoException (net.js:904:11)
      at connect (net.js:766:19)
      at net.js:845:9
      at dns.js:72:18
      at process._tickCallback (node.js:419:13)
info kIet SBOT 285 disconnect 
info kIet SBOT 286 connect
  {
    "host": "grimwire.com",
    "port": 2000,
    "time": {
      "connect": 1421999503513,
      "attempt": 1422010340164
    },
    "connected": true,
    "id": "64FmNkolarZeXMldJAKwj9E54XwXJdubIqD1sPPCgCQ=.blake2s",
    "failure": 1
  }
warn kIet SBOT 286 unauthed
  Error: getaddrinfo ENOTFOUND
      at errnoException (dns.js:37:11)
      at Object.onanswer [as oncomplete] (dns.js:124:16)
info kIet SBOT 286 disconnect 
```

both connections are available and neither peer has a failure rate high enough to keep them from getting selected. is it possible the timeout for connection scheduling needs to be reset?

**Comment by pfraze** [comment]
seems to happen on my macbook but not on my windows machine

> both connections are available

by this i meant theyre not in use -- gossip only allows 2 connections at a time
