### ISSUE TITLE
sbot crash

### ISSUE THREAD

**Issue by noffle** [ssbc/scuttlebot#95]
I'm not exactly sure what triggered this (I noticed the server was dead only after coming back a bit later), but I did start following `dominic` (and so `dominic's_linode_server` got added to my server list) pretty shortly before that. Lemme know if there's anything I can dig deeper on.

```
info DW1i SBOT 18 incoming-connection 
warn DW1i SBOT 18 unauthed
  Error: method not supported:auth
      at Object.PacketStream.request (http://localhost:2000/js/home.js:10764:23)
      at onRequest (http://localhost:2000/js/home.js:10994:12)
      at Object.p.write (http://localhost:2000/js/home.js:11141:33)
      at http://localhost:2000/js/home.js:11333:15
      at http://localhost:2000/js/home.js:10094:33
      at http://localhost:2000/js/home.js:10377:9
      at http://localhost:2000/js/home.js:12622:9
      at http://localhost:2000/js/home.js:12546:7
      at pull (http://localhost:2000/js/home.js:12211:9)
      at next (http://localhost:2000/js/home.js:12236:11)
info DW1i AUTH 18 req "luy/tFqWzdYTrMles/hoannfsau1JDhMMPA+dIjMS7M=.blake2s"

TypeError: Property 'read' of object #<Object> is not a function
    at Object.stream.destroy (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:70:18)
    at /usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:188:11
    at Array.forEach (native)
    at Object.p.destroy (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:185:17)
    at Object.p.write (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:171:24)
    at /usr/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:47:35
    at loop (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/sinks.js:11:20)
    at /usr/lib/node_modules/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/throughs.js:97:9
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-stream/throughs.js:97:9
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-stream/throughs.js:21:7
```

**Comment by pfraze** [comment]
thanks, we'll look into it

**Comment by pfraze** [comment]
i feel like we handled this already. muxrpc is using `~0.4.1`, which i think SHOULD get `0.4.2`, but is it possible that it got `0.4.1` instead and didnt get this: https://github.com/dominictarr/packet-stream/commit/56b7cafcf65f7bde56661389feecd1cdd4c4f7be ?

@noffle can you tell me what version of packet-stream is getting used? it should be in `$NPM-GLOBAL-LIB/scuttlebot/node_modules/muxrpc/node_modules/packet-stream`

**Comment by noffle** [comment]
Alas, it's `0.4.2` over here for `packet-stream`. :(

**Comment by pfraze** [comment]
oh well, no free fixes this time. thanks for checking.

**Comment by dominictarr** [comment]
ssb has changed heaps since this, closing
